# Video game database

Since the 1980s, video games have become an increasingly important part of the entertainment industry, and whether they are also a form of art is a matter of dispute.
With the growth of the market of video game, the development teams became more and more huge. Typically, a video game console development team can range in sizes of anywhere from 5 to 50 people, with some teams exceeding 100. 

In this case, we create a video game database for both development team and video game player. On the one hand, this database including game information and review which can provide a feedback to publisher. On the other hand, video game player can easily choose game from given information and have better game

The first step is to use social media api to get data

In [3]:
import twitter
import json
import pandas as pd
CONSUMER_KEY = "40M3D2d9haFTmWiHUOqO3Wx7p"  
CONSUMER_SECRET = "FYdSd8Jcr5OmwQclQ1q1QwPLTwbVw3fX8Z35igJfqzmzLZp8d3"  
OAUTH_TOKEN = "1103068796036759552-iNLmsLjgYBODHZ1RcZBdsHG7g3d5wt"  
OAUTH_TOKEN_SECRET = "STv0EL4lsyamXzIYy6CZRE2wmml3toKuXQd5QDIV6nKtZ"  


api = twitter.Api(consumer_key=CONSUMER_KEY,
                      consumer_secret=CONSUMER_SECRET,
                      access_token_key=OAUTH_TOKEN,
                      access_token_secret=OAUTH_TOKEN_SECRET)
#authorize the api

In [6]:
public_posts =[]
for i,x in enumerate(api.GetSearch(term='hearthstone',count = 50)):
    public_tweet=dict()
    public_tweet['name'] = json.loads(str(x))['user']['name']
    public_tweet['id'] = json.loads(str(x))['id']
    public_tweet['followers'] = json.loads(str(x))['user']['followers_count']
    public_tweet['post'] = json.loads(str(x))['text']
    try: public_tweet['favourites'] = json.loads(str(x))['favorite_count']
    except: public_tweet['favourites'] = 0
    if         public_tweet['favourites'] == 0:
        try: public_tweet['favourites']=json.loads(str(x))['user']['favourites_count']
        except:public_tweet['favourites'] = 0
    try:public_tweet['retweet'] = json.loads(str(x))['retweet_count']
    except:public_tweet['retweet']=0
    public_tweet['hashtag'] = json.loads(str(x))['hashtags']
    public_tweet['statuses'] = json.loads(str(x))['user']['statuses_count']
    public_tweet['created_at'] = json.loads(str(x))['created_at']
    public_posts.append(public_tweet)
#get post which include'overwatch',return 100 results.And, save it in the arries

In [7]:
public_tweets_df = pd.DataFrame(public_posts)
public_tweets_df = public_tweets_df[['id','name','post','followers','created_at','retweet','favourites','statuses','hashtag']]
public_tweets_df
#use pandas, save it in the schema

,id,name,post,followers,created_at,retweet,favourites,statuses,hashtag
0,1121237240288563200,Hearthstone,"Win or lose, Stonebrew’s Tavern is a place to ...",877698,Thu Apr 25 02:19:24 +0000 2019,833,3355,17922,[]
1,1121244415064887296,Hearthstone: ハースストーン,ストーンブルーの酒場では勝っても負けても、実力伯仲の戦いを讃え、見事な一手に歓声が上がり、「...,37623,Thu Apr 25 02:47:54 +0000 2019,191,315,4706,[{'text': 'ハースストーン'}]
2,1121345866109992960,Hearthstone España,"Ganes o pierdas, la taberna de Bernero es un l...",48634,Thu Apr 25 09:31:02 +0000 2019,54,146,7270,[]
3,1121942491056562176,Samantha J. Foster Composer,RT @Kotaku: Archivist Elysiana is a fun Hearth...,4064,Sat Apr 27 01:01:49 +0000 2019,1,24824,198736,[]
4,1121942444893929472,Hsfan,RT @ecoutepasca_HS: In the final of Hearthston...,1,Sat Apr 27 01:01:38 +0000 2019,1,87,85,[]
5,1121942088025878529,Kotaku,"Archivist Elysiana is a fun Hearthstone card, ...",2089597,Sat Apr 27 01:00:13 +0000 2019,1,4,80788,[]
6,1121941815626649601,カニミソ,RT @toilet_mania: #Hearthstone\nテンポ回復ドルイドでレジェン...,151,Sat Apr 27 00:59:08 +0000 2019,15,4477,40851,[{'text': 'Hearthstone'}]
7,1121941629852704768,ecoutepasca,In the final of Hearthstone Masters Qualifier ...,671,Sat Apr 27 00:58:23 +0000 2019,1,1,710,[]
8,1121941002141478912,Wall-E,Filmes que não tinham o MENOR direito de fazer...,538,Sat Apr 27 00:55:54 +0000 2019,0,201734,62261,[]
9,1121940911875854336,NerdyFlow,RT @HS_mathematics: #Dalaran was attacked by t...,704,Sat Apr 27 00:55:32 +0000 2019,1,20869,18097,[{'text': 'Dalaran'}]
10,1121940206725345281,Hearthstone Mathematics,#Dalaran was attacked by the League of EVIL.\n...,172,Sat Apr 27 00:52:44 +0000 2019,1,1,185,[{'text': 'Dalaran'}]
11,1121939868450320384,えくすぴあ,RT @toilet_mania: #Hearthstone\nテンポ回復ドルイドでレジェン...,580,Sat Apr 27 00:51:23 +0000 2019,15,183,13811,[{'text': 'Hearthstone'}]
12,1121939690909835265,Joint #1 autimatic fan,I miss old forsen. \nI miss old hearthstone.\n...,97,Sat Apr 27 00:50:41 +0000 2019,0,781,336,[]
13,1121939058408574977,がいがい,RT @toilet_mania: #Hearthstone\nテンポ回復ドルイドでレジェン...,131,Sat Apr 27 00:48:10 +0000 2019,15,1210,4535,[{'text': 'Hearthstone'}]
14,1121938599732113408,メガゴリケロ,RT @toilet_mania: #Hearthstone\nテンポ回復ドルイドでレジェン...,96,Sat Apr 27 00:46:21 +0000 2019,15,4151,27233,[{'text': 'Hearthstone'}]
15,1121938570854522881,Andy,#Hearthstone #WildHs #RiseOfShadows,207,Sat Apr 27 00:46:14 +0000 2019,0,13592,17917,"[{'text': 'Hearthstone'}, {'text': 'WildHs'}, ..."
16,1121938485907091456,ahirun,RT @toilet_mania: #Hearthstone\nテンポ回復ドルイドでレジェン...,38981,Sat Apr 27 00:45:54 +0000 2019,15,75879,34208,[{'text': 'Hearthstone'}]
17,1121938387185876993,I’m Big Lou,"RT @Matthieist: When the title is cut off, you...",170,Sat Apr 27 00:45:30 +0000 2019,13,40606,12154,[]
18,1121938269372125184,"Tyrman ""Mad Dog"" Bladebreaker","@Minnow_WRA @PancakeMix85 ""It was the same tab...",804,Sat Apr 27 00:45:02 +0000 2019,0,2,5801,[]
19,1121938021387882497,freedom chimpanzee 佐藤,RT @koide9919: #106 脳死ゲームすな編\n\nおかげさまで選挙カーの爆音が...,1272,Sat Apr 27 00:44:03 +0000 2019,0,79883,11497,[]
20,1121937895831400449,Jonathan Andrist,Going to try counter-queuing this deck into my...,551,Sat Apr 27 00:43:33 +0000 2019,0,32875,53487,[]
21,1121937855893442566,Santoro 🐍,o Qi da galera do hearthstone é 8000+,51,Sat Apr 27 00:43:24 +0000 2019,0,2860,1846,[]
22,1121937407731855361,HearthStudy,RT @toilet_mania: #Hearthstone\nテンポ回復ドルイドでレジェン...,188,Sat Apr 27 00:41:37 +0000 2019,15,7128,5405,[{'text': 'Hearthstone'}]
23,1121937186243452928,Eugene Mulberry,"RT @PlayHearthstone: Win or lose, Stonebrew’s ...",7,Sat Apr 27 00:40:44 +0000 2019,833,9,7,[]
24,1121936728636448768,oof,RT @HornedLyzz: Saw the last short animation o...,166,Sat Apr 27 00:38:55 +0000 2019,498,54825,24442,[]
25,1121936672818524160,えびろう,RT @hearthstone_exp: #ハースストーン のReddit (/r/hear...,304,Sat Apr 27 00:38:42 +0000 2019,12,1223,915,[{'text': 'ハースストーン'}]
26,1121936654812483584,Sushil kumar,Hearthstone Rise of the Shadows Is Fun for Reg...,285,Sat Apr 27 00:38:37 +0000 2019,0,24,181380,[]
27,1121936648244219904,Revenge News,Hearthstone Rise of the Shadows Is Fun for Reg...,45,Sat Apr 27 00:38:36 +0000 2019,0,0,115259,[]
28,1121936151273721856,🌸Wing Wolf🌸,RT @HornedLyzz: Saw the last short animation o...,964,Sat Apr 27 00:36:37 +0000 2019,498,190147,163091,[]
29,1121935370176823297,@thechangingtime,RT @endemicesports: 🗣 PARTNER ALERT! 🗣\n\nJust...,63,Sat Apr 27 00:33:31 +0000 2019,289,6,2072,[]
30,1121935329047527429,ziv,I’m playing a druid token meta deck in hearths...,163,Sat Apr 27 00:33:21 +0000 2019,0,1,3048,[]
31,1121935209643909120,がり,RT @hearthstone_exp: #ハースストーン のReddit (/r/hear...,177,Sat Apr 27 00:32:53 +0000 2019,12,6613,2101,[{'text': 'ハースストーン'}]
32,1121935179868725248,Mike Osmond,RT @endemicesports: 🗣 PARTNER ALERT! 🗣\n\nJust...,26,Sat Apr 27 00:32:46 +0000 2019,289,78,4036,[]
33,1121935059789991936,Chris Holloway,RT @HSTopDecks: Check out @XilinhungHS's #31 L...,48,Sat Apr 27 00:32:17 +0000 2019,6,699,4870,"[{'text': 'Hearthstone'}, {'text': 'RiseOfShad..."
34,1121934908413358085,FamilyFriendlyGaming,Thank you for your support of our #TWitch stre...,2124,Sat Apr 27 00:31:41 +0000 2019,0,3,18231,"[{'text': 'TWitch'}, {'text': 'Hearthstone'}]"
35,1121934796228190208,Duane aka Mageadeath,Friday Night Arena starts NOW! Come hang out a...,944,Sat Apr 27 00:31:14 +0000 2019,0,2,10030,[]
36,1121934725730357248,poté,RT @hearthstone_exp: #ハースストーン のReddit (/r/hear...,267,Sat Apr 27 00:30:57 +0000 2019,12,913,18457,[{'text': 'ハースストーン'}]
37,1121934542972047366,/r/hearthstone,RoS Deck Spotlight #2 – Big Shaman https://t.c...,1608,Sat Apr 27 00:30:14 +0000 2019,0,96,20572,[]
38,1121934040746086400,Just Push Play (Ottawa),RT @Kotaku: Archivist Elysiana is a fun Hearth...,2049,Sat Apr 27 00:28:14 +0000 2019,4,37554,79519,[]
39,1121933965776941056,Ironclad invincible Nick,RT @InvenGlobal: 🏆🎮 @Bunnyhoppor on his World ...,1489,Sat Apr 27 00:27:56 +0000 2019,2,3199,4680,[]
40,1121933928569421825,pygmillion ass bitch,RT @HornedLyzz: Saw the last short animation o...,79,Sat Apr 27 00:27:47 +0000 2019,498,30496,3878,[]
41,1121933789129633792,Ironclad invincible Nick,We got you covered for all things #HCT includi...,1489,Sat Apr 27 00:27:14 +0000 2019,0,3199,4680,[{'text': 'HCT'}]
42,1121933717054742528,Division,RT @UltiStreams: Live trying out the new #For...,147,Sat Apr 27 00:26:57 +0000 2019,2,1521,619,[{'text': 'FortniteXAvengers'}]
43,1121933562918445057,Welford,I'm now streaming on Twitch! Playing Hearthsto...,9,Sat Apr 27 00:26:20 +0000 2019,0,2,127,[]
44,1121933392830795776,_Blissssss,RT @FlightEsportsAU: How bad do you want it?\n...,45,Sat Apr 27 00:25:40 +0000 2019,2,433,85,[]
45,1121933285905575936,DarkCalculusHS,"Got legend this month with Nomi Priest, I thin...",15,Sat Apr 27 00:25:14 +0000 2019,0,19,84,[]
46,1121932931512061953,José de Matías,"@R_Electriko El Ajedrez es un deporte mental, ...",16374,Sat Apr 27 00:23:50 +0000 2019,0,3,56365,[]
47,1121932785021792256,KUB,@DuwinHS @EK_Hearthstone Looks fun ... insta-c...,2,Sat Apr 27 00:23:15 +0000 2019,0,14,26,[]
48,1121932718982430720,A gɑthɑ | spoiler de got,tô lendo mc online em um blog e a dona do blog...,319,Sat Apr 27 00:22:59 +0000 2019,0,13625,9760,[]
49,1121932169771982848,☽Hai In The Sky☾,RT @HornedLyzz: Saw the last short animation o...,127,Sat Apr 27 00:20:48 +0000 2019,498,12952,8138,[]

In [ ]:
public_tweets_df.to_csv("overwatch",index=False,sep=',')
#saved as csv

In [8]:
SCREEN_NAME="playoverwatch"
results = api.GetUserTimeline(screen_name=SCREEN_NAME,count = 100)

posts =[]
favourites =[]
retweets = []
time = []
user_id = []
name = []
followers = []
hashtags = []

for each in results:
    status = json.loads(str(each))
    posts.append(status['text'])
    try:
        favourites.append(status['favorite_count'])
    except:
        favourites.append(status['retweeted_status']['favorite_count'])
    
    try: retweets.append(status['retweet_count'])
    except: retweets.append('0')
    time.append(status['created_at'])
    user_id.append(status['user']['id'])
    followers.append(status['user']['followers_count'])
    name.append(status['user']['name'])
    try:
        hashtags.append(status['hashtags'][0]['text'])
    except:
        hashtags.append(status['hashtags'])

print([s for s in posts])

#get information from 'playhearthstone' homepage

['RT @AzuraLynx: 🌑🌙Mercy Atlantic All Stars Skin 💜💜💜#Overwatch @PlayOverwatch https://t.co/U2QPLpfJ49', "@lolmaowtfXD @iiweirdness @officialvalkia @soliteary We're all members of the same community. https://t.co/BiIsTIroeX", '@HellPharah https://t.co/Ubn9CD1S9m', '@GZCharge We all do.', '@catgirlneko @ddaenglalisa https://t.co/sYwMIGwWec', "RT @overwatchleague: Gear up for #OWL2019 All Stars with legendary skins for 200 tokens each!\n\nHere's the All-Star action going down:\nTalen…", '&gt; Accessing archived file...\n\nDecryption status: COMPLETE\n\n📂 STORM RISING INTEL EXAMINATION – MAXIMILIEN https://t.co/IlFyuhVF5D', '@byeless2 Overwatch loves you.', '@yonatanbait Snag your flags and face paint!', 'Witness players become heroes.\n\nThe Overwatch World Cup is back! ￼￼\n\n 🌎🏆 https://t.co/iE9zg3Qbzi https://t.co/7upvzwvTik', "@Blizzard_Ent Let's get this party STARTED!! 🐸🎶 https://t.co/1JWswjcgow", 'RT @Blizzard_Ent: BlizzCon 2019 will be November 1-2 at the Anaheim Convention Center!  New this year: BlizzCon Pregame Festivities, new ti…', 'RT @DanielFenner: The new workshop feature in @PlayOverwatch is INCREDIBLE, there are going to be so many amazing custom games made with it…', '@Top2Bottom2345 🤔🤔🤔🤔🤔🤔😏', "@MMrby69 It's currently on the PTR.", '@coralines Overwatch loves you.', 'Roll up your sleeves and show us a marvel of engineering!\n\nIntroducing the Overwatch Workshop—create a Script to ad… https://t.co/tKY7SfTV0x', "@ChengduHunters Here's a guide, practice makes perfect! https://t.co/fT2939blDJ", '@ItsTripleAye https://t.co/Pe2Yx6detN', '@TorontoDefiant https://t.co/2wLQMkcA4W', '@ZekZebZab Read up on more info here: https://t.co/fT2939blDJ', '@kristinaspaige Enable captions fam 😉', "Assemble your ideas because there's work to be done! 💡🔨 \n\nGame Director Jeff Kaplan lays the groundwork on Overwatc… https://t.co/nVq5VxI1nk", "RT @art_cerealex: ☠️ Deadlock McCree 🤠\nThis event's skins are so good!!\n#Overwatch #OverwatchFanart https://t.co/0JttKDyBRa", 'RT @fayren: Is this really necessary? https://t.co/dnvFXW04DL', '@Ayana_Mudou https://t.co/BjFGQm8d9a', "@Ashe____0 We're humbled by our community. Thank you!", '@GVBBlE 👍', 'Never accept the world as it appears to be, dare to see it for what it could be.\n\nHappy #EarthDay, heroes. https://t.co/POOnPBEi5T', '@GrandpaBats Most impressive.', 'RT @GrandpaBats: Surrender to my will... #overwatch #Moira https://t.co/aKhdpmAu84', '@TheMasterKrook 😉 https://t.co/aulfr1nA5j', '@RapidRapidash We appreciate your feedback.', 'Don’t let him escape. 🤖 Assemble your strike team and join the chase! \n\nPlay Overwatch FREE through April 23 on PC,… https://t.co/wia7yMOts6', 'RT @anhdangerous: Ashe Socialite weapon concept I made for the Overwatch Storm Rising event https://t.co/8ok9Z6RXqX', "RT @NatesonOfficial: https://t.co/LWuJSuN9l7 Let's get some SWEET games in today. Live right now!! @PlayOverwatch https://t.co/INIWHoH4dC", '@Stylosa Indeed, it is Escort, not Assault.', '@LAGladiators Correct. It is an Escort map! Apologies for the confusion.', 'Captivating oceanfront. 🏖️ \nUnbelievable artistry. 🎨 \nBeaming sunshine. ☀️ \nAwesome music. 🎺 \n\nWhat are you waiting… https://t.co/fIioRkuBWJ', '@beybarro https://t.co/hJQgLFSBSu', "@TheMasterKrook We're glad you dig it. 👍", 'This apparel is no longer confidential! \n\nReveal your allegiance with new Archives Gear available in the… https://t.co/UNCLmWRq9H', 'RT @macchama674: ハイローラーハモンドとネズミジャンクラと科学者モイラ🐹🐭⚗️\n#Overwatch #オーバーウォッチ #OWアート https://t.co/35RKnH0Gzv', 'RT @KisumiMizkatt: Thank you Blizzard, I love him 💕💕💕\n#Overwatch #OverwatchFanart https://t.co/FeSsihYjVs', "@bones_ablaze We'd recommend you completely exit the application and restart the game.", '@literalgarbagio https://t.co/iKCVj0FtdS', '@anarchpls https://t.co/XaZzVNSNpa', '⚠️ EMERGENCY ALERT \n\nHurricane Warning in this area until 5.6.19. Check local media and Jeff Kaplan for an update o… https://t.co/W2lkeqqsQH', 'RT @ohnickel: 🚨 LIVE 🚨 FROM BLIZZARD HQ! Playing The New @PlayOverwatch Event W/ Special Guest Jeff Kaplan! \n\nWatch here: https://t.co/HAuu…', '@SkylarStorm25 This patch features a remaster that impacts players on console. Benefits to this remaster are load t… https://t.co/rx0Ks4RRaj', '@BostonUprising 😎', '@coeurduparis Hey all, this patch features a remaster that impacts players on console. Benefits to this remaster is… https://t.co/3tGTpyvyCh', 'PRIORITY: 1⃣ \n\nOverwatch "Storm Rising," "Retribution," and "Uprising" file status: OPEN. \n\n📂 Initiating mission pl… https://t.co/BGpNX3QtN5', '@Stylosa https://t.co/BZpa9eYO4j', 'RT @AzuraLynx: and I just could not pass by) SOCIALITE ASHE skin! 💜 https://t.co/zDVMRii4sF', "@mxmtoon @alienoverlorde He's always keeping it classy.", '@Cooziie We appreciate your feedback.', '@Muma https://t.co/lXweJqxE1K', '@Cooziie @R3AP3ROVS0UL5 Noted ✌️', 'You have to watch out for the one percent. \n\nKeep it bougie as SOCIALITE ASHE (Legendary!) \n\nChase the truth: April… https://t.co/DkjWBf6zxl', "RT @hage_2013: Couldn't resist drawing Formal:76...🎖️ https://t.co/FV6TOeHkGC", '@Geehawst Why not?', '@SFShock Get. It.', '@GZCharge You best be. 😎', '@R3AP3ROVS0UL5 Safety first. ALWAYS. \n\nHelmets are cool 👍', '@Stylosa Roll that track!\n\n▶️ The Son of Flynn https://t.co/RwZnCfVtte', 'Decryption status: COMPLETE\n\nTarget located. Overwatch Strike Team deployed. Chase the truth. 🔎\n\nPrepare for Storm… https://t.co/M4Hb1UT1ED', "RT @ufficiosulretro: Quick sketch of the golden boy. My hand slipped because I'm weak for uniforms. Hope to see more Formal skins in the fu…", 'Brace for the race.\n\nPut the pedal to the metal as RACER ZARYA (Epic)!\n\nChase the truth: April 16 🔎… https://t.co/8KKbDT08S9', 'A phantom emerges off the coast of Busan.\n\nTerrorize your enemies as GWISHIN BASTION (Legendary)!\n\nChase the truth:… https://t.co/KM5OeQLuep', '💰 Follow the money. \n🤖 Find Maximilien. \n🔎 Chase the truth. \n\nOverwatch Storm Rising begins April 16! 🎨 by… https://t.co/Ap2JIooPLi', '@IPreferChef https://t.co/HxkdZVK9wX', "Save the medals, I've had my fill. 🎖️\n\nCommemorate your glory as FORMAL: 76 (Legendary)!\n\nChase the truth: April 16… https://t.co/E6oqXwENJb", '@Doctor_Yiggles Get. It.', '@FoxyLover115 Indeed, it is an Epic.', "@PlayStation You've gotta risk it for the biscuit.\n\nBet on victory as HIGH ROLLER WRECKING BALL (Epic)!\n\nOverwatch… https://t.co/7DvURzWs00", '@AdelCODz https://t.co/3WAvM23QPB', "RT @PlayStation: Roll with style 🕶️\n\nBehold Hammond's High Roller Wrecking Ball skin, coming to Overwatch April 16: https://t.co/mRHFStuyub…", 'RT @avedral: Soo... I drew the new #Moira skin (sorta), while I should have been doing some concept drawing for work. :) #Overwatch https:/…', '@heaIsIuto3o https://t.co/p9W8xNJ3Iz', "@SirKuno We're glad you dig it.", '@VonHollde 😂', '@Frosty_U_ Overwatch loves you.', "@LolaTempest We'll pass along the kind words. Thank you!", 'Saddle up with the infamous outlaw gang. 🌵\n\nGo on the run as DEADLOCK MCCREE (Legendary)!\n\nChase the truth: April 1… https://t.co/3sQywxl8Lf', '@AngelosFrag Thank you for your feedback!', 'Spring for these deals!\n  \nDash to the #BlizzardGear store to rejuvenate your collection!\n  \n👉… https://t.co/xehag5D7hv', '@SilenS99 https://t.co/1Hn7Ndd2gu', '@DallasFuel https://t.co/2crxX3REBB', 'RT @maro_chick: 모두 여길 봐주세요~ https://t.co/oaP6KqW8Vu', '@gamewatchtoday It was inevitable.', '@forestsknight What an interesting hypothesis.', '@TheMasterKrook Much obliged.', '@SilenS99 Predictable. 🧪', '@MoiraDeodorant https://t.co/18d8gO9beO', 'Science will reveal the truth.\n\nFind your element as SCIENTIST MOIRA (Legendary)!\n\nChase the truth: April 16 🔎… https://t.co/RA9yTjlKKB', '@TheMasterKrook @Xbox Alright Krook, you win this round. 👏', "@Xbox Heroes, come out and play.\n\nStart clownin' around as CIRCUS JUNKRAT (EPIC)!\n\nOverwatch Storm Rising begins Ap… https://t.co/5fbAku9naW", 'RT @Xbox: It’s a perfect day for some mayhem.\n\nChase the truth April 16: https://t.co/HZA20qwoZJ https://t.co/RfE4nPqYuS', '@FortniteTapohi I got you. https://t.co/scTHecaq0a']

In [9]:
import pandas as pd
df_1 = pd.DataFrame(data = name, columns = ['Name'])
df_1['User_id'] = user_id
df_1['Followers'] = followers
df_1['Post'] = posts
df_1['Hashtags'] = hashtags
df_1['Posted_time'] = time
df_1['Favourites'] = favourites
df_1['retweets'] = retweets
#saved in the schema

In [ ]:
df_1.to_csv("overwatchpage",index=False,sep=',')#saved in csv

# 10 Use cases
first to use pymysql connect mysql use python.

In [10]:
import pymysql
import pymysql.cursors
import numpy as np
import pandas as pd
import pprint as pp



db=pymysql.connect(host='localhost',
                          user='root',
                          password='CLOW940426ZTS',
                          db='project',
                          port=3306,
                           charset='utf8'
                          )

In [11]:
cursor=db.cursor()

In [12]:
def sql_to_df(sql_query):
    df=pd.read_sql(sql_query,db)
    return df

1.What are people saying about me (somebody)? 
I think this question needs to choose tag first. We can choose a tag to represent a video game, and then search all the comments that have this tag. Then We can get that what people are saying about pokemon. So I choose pokemon As my tag, then search from game table, get the post ,then collect them.

In [13]:
sql="Select post from project.game where post like '%pokemon%'"
sql_to_df(sql)

                                                 post
0   RT @nickturani: A quick guide on the subtle di...
1   purehavuk Gaming #News | Pokémon Go guide: How...
2   Pokémon Go guide: How to get Shiny Pokémon htt...
3   Pokémon Go guide: How to get Shiny Pokémon htt...
4   Pokémon Go guide: How to get Shiny Pokémon htt...
5   Pokémon Go guide: How to get Shiny Pokémon htt...
6   Pokémon Go guide: How to get Shiny Pokémon htt...
7   Pokémon Go guide: How to get Shiny Pokémon htt...
8   Pokémon Go guide: How to get Shiny Pokémon htt...
9   Pokémon Go guide: How to get Shiny Pokémon htt...
10  【ポケモンgo】対人戦スーパーリーグ　3　完全攻略　最強パーティ教えちゃいます！【pokem...
11  【ポケモンgo】対人戦スーパーリーグ　3　完全攻略　最強パーティ教えちゃいます！【pokem...
12  RT @miketendo64: [Guide] How to Earn the #Melm...
13  RT @miketendo64: [Guide] How to Earn the #Melm...
14  The Weekend Guide: Fishing Derby, Spring Craft...
15  I want to #Win a copy of The Ultimate #Pokemon...
16  RT @PokemonArtFacts: Happy Earthday! According...
17  Pokémon Go guide: Encounters and Field Researc...
18  Pokemon Go guide: Everything you need to becom...
19  RT @jwlawson01: I’ve had a lovely afternoon li...
20  @gaymer629 Hi Trainer, chances are there that ...
21  RT @nickturani: A quick guide on the subtle di...
22  RT @nickturani: A quick guide on the subtle di...
23  @Awope_ @Guide____ But Pokémon ain’t weird bro...
24  Pokemon GO: Guide To Obtaining Sinnoh Stones -...
25  Review: Carlton Books - The Ultimate Pokemon T...
26  Niantic has introduced a number of new challen...
27  Blessings upon whoever created this Pokemon DV...
28  I’ve had a lovely afternoon listening to our s...
29  ?Pokemon Private Tour of Sofia ?\n?In this wal...
..                                                ...
35  I want to #Win a copy of The Ultimate #Pokemon...
36  RT @PokemonArtFacts: Happy Earthday! According...
37  Pokémon Go friendship guide: How to get Lucky ...
38  Pokémon Go guide: Field Research Tasks and enc...
39  RT @nerdalert2014: I want to #Win a copy of Th...
40  RT @n64thstreetgifs: Money-minded Meowth in Po...
41  RT @GamePress_PoGO: Our Absol Solo Raid Guide ...
42  Win Tickets To Pokemon: Detective Pikachu ? - ...
43  Pokémon Go guide: Field Research Tasks and enc...
44  #Pokemon #GameboyAdvance Ruby And Sapphire Ver...
45  RT @CindyBearsDen: Official #Pokemon Pokedex b...
46  RT @PokemonArtFacts: Happy Earthday! According...
47  Official #Pokemon Pokedex by Tracey West https...
48  purehavuk Gaming #News | Pokémon Go guide: Fie...
49  RT @NedHartley: The Pokémon book that I wrote ...
50  Pokémon Go guide: Field Research Tasks and enc...
51  Pokémon Go guide: Field Research Tasks and enc...
52  RT @PokemonArtFacts: Happy Earthday! According...
53  Pokémon Go guide: Field Research Tasks and enc...
54  Pokémon Go guide: Field Research Tasks and enc...
55  Pokémon Go guide: Field Research Tasks and enc...
56  Pokémon Go guide: Field Research Tasks and enc...
57  Pokémon Go guide: Field Research Tasks and enc...
58  Pokémon Go guide: Field Research Tasks and enc...
59  Pokémon Go friendship guide: How to get Lucky ...
60  RT @PokemonArtFacts: Happy Earthday! According...
61  RT @PokemonArtFacts: Happy Earthday! According...
62  RT @PokemonArtFacts: Happy Earthday! According...
63  The Pokémon book that I wrote is out next week...
64  I want to #Win a copy of The Ultimate #Pokemon...

[65 rows x 1 columns]

2.How viral are my posts? 
According to the example, the viral of the posts is reflecting on the favs and retweets. Here, I define :
viral=0.7*retweets+0.3*favs
then calculate the viral of its viral of posts, then average the viral, get the final viral of its posts. So the first step is that I have to grasp twitters from one game(here, I use hearthstone homepage) and then use my varl equal, get the average of viral.

In [14]:
sql="SELECT name,User_id,Posted_time,post,Favourites,retweets,(0.3*Favourites+0.7*retweets) as viralofmypost FROM project.playhearthstone order by viralofmypost desc"
sql_to_df(sql)

,name,User_id,Posted_time,post,Favourites,retweets,viralofmypost
0,Hearthstone,1209608880,Wed Mar 27 22:59:07 +0000 2019,RT @YukieTAJIMA: 【Hearthstone】今年もあの日が近づいてきました\...,6670,2324,3627.8
1,Hearthstone,1209608880,Thu Apr 25 14:24:45 +0000 2019,RT @Blizzard_Ent: BlizzCon 2019 will be Novemb...,3459,803,1599.8
2,Hearthstone,1209608880,Thu Apr 25 02:19:24 +0000 2019,"Win or lose, Stonebrew’s Tavern is a place to ...",3167,780,1496.1
3,Hearthstone,1209608880,Mon Apr 08 19:42:27 +0000 2019,We’re thrilled to announce that tomorrow’s rel...,1472,312,660.0
4,Hearthstone,1209608880,Thu Apr 25 07:01:11 +0000 2019,"RT @HSesports: ✨ And just like that, we're in ...",1161,152,454.7
5,Hearthstone,1209608880,Thu Apr 04 21:30:01 +0000 2019,"Starting today, login on either iOS, Android, ...",801,189,372.6
6,Hearthstone,1209608880,Fri Mar 22 17:00:24 +0000 2019,"What will Madame Lazul find,\nwhen she gazes i...",887,138,362.7
7,Hearthstone,1209608880,Wed Mar 27 00:08:36 +0000 2019,RT @DekkiGamesJP: 【新カード独占公開】ゲームコミュニティDEKKIは #ハ...,473,246,314.1
8,Hearthstone,1209608880,Tue Apr 09 17:09:49 +0000 2019,"The League of E.V.I.L. has assembled, their ta...",629,94,254.5
9,Hearthstone,1209608880,Wed Apr 17 09:31:30 +0000 2019,RT @Thats_TowelieHS: @PlayHearthstone 'Member ...,651,69,243.6
10,Hearthstone,1209608880,Thu Apr 04 14:00:08 +0000 2019,The Rise of Shadows card reveals have been com...,550,65,210.5
11,Hearthstone,1209608880,Wed Mar 20 20:09:06 +0000 2019,Join us for our first #RiseOfShadows card reve...,521,71,206.0
12,Hearthstone,1209608880,Tue Apr 02 17:00:33 +0000 2019,Watch some of your favorite streamers craft de...,557,51,202.8
13,Hearthstone,1209608880,Thu Apr 04 19:00:02 +0000 2019,"Login to claim Archmage Vargoth, for free! Thi...",437,85,190.6
14,Hearthstone,1209608880,Mon Apr 01 18:01:02 +0000 2019,"Join Brian Kibler, Senior Hearthstone Designer...",425,67,174.4
15,Hearthstone,1209608880,Tue Mar 26 20:00:01 +0000 2019,Don't forget to login between now and April 2 ...,393,70,166.9
16,Hearthstone,1209608880,Tue Apr 16 12:27:03 +0000 2019,RT @DorianGorr: @PlayHearthstone When Khadgar ...,439,43,161.8
17,Hearthstone,1209608880,Wed Apr 17 23:54:17 +0000 2019,RT @DaveKosak: Okay #Hearthstone villains and ...,447,39,161.4
18,Hearthstone,1209608880,Tue Apr 23 15:54:26 +0000 2019,RT @HSesports: Twitch Drops are inbound for th...,346,72,154.2
19,Hearthstone,1209608880,Wed Apr 03 20:32:11 +0000 2019,Take a look at every card coming to Hearthston...,332,70,148.6
20,Hearthstone,1209608880,Mon Apr 08 21:21:52 +0000 2019,RT @PlayHearthstone: Something evil is assured...,326,52,134.2
21,Hearthstone,1209608880,Fri Apr 05 17:01:00 +0000 2019,"Something evil is assuredly afoot, and it has ...",326,52,134.2
22,Hearthstone,1209608880,Tue Apr 02 14:55:29 +0000 2019,RT @G2Thijs: Thanks Blizzard for giving me a c...,403,18,133.5
23,Hearthstone,1209608880,Fri Apr 12 08:12:48 +0000 2019,RT @HSesports: Meet Europe's legendary lineup ...,304,55,129.7
24,Hearthstone,1209608880,Wed Apr 17 17:00:02 +0000 2019,Starting today you can grab a basketful of boo...,307,49,126.4
25,Hearthstone,1209608880,Thu Mar 21 17:05:44 +0000 2019,Join Game Designer Chadd Nervig as he introduc...,311,45,124.8
26,Hearthstone,1209608880,Tue Apr 02 19:29:51 +0000 2019,RT @HSesports: IN JUST 3 WEEKS the top 16 play...,286,55,124.3
27,Hearthstone,1209608880,Tue Apr 16 12:25:37 +0000 2019,RT @SilentNickHS: @PlayHearthstone #RiseOfShad...,313,40,121.9
28,Hearthstone,1209608880,Wed Mar 27 17:34:16 +0000 2019,RT @HSesports: The pinnacle of Hearthstone esp...,255,63,120.6
29,Hearthstone,1209608880,Mon Mar 25 16:47:55 +0000 2019,The first card reveal livestream is now live! ...,264,53,116.3
...,...,...,...,...,...,...,...
70,Hearthstone,1209608880,Sat Mar 30 19:49:53 +0000 2019,Sending the streets of Dalaran into chaos! #Ri...,122,10,43.6
71,Hearthstone,1209608880,Thu Apr 18 17:00:02 +0000 2019,Choose Your Champion is back for the HCT World...,98,19,42.7
72,Hearthstone,1209608880,Sat Mar 30 19:49:52 +0000 2019,As sinister plots are put into action by power...,123,8,42.5
73,Hearthstone,1209608880,Tue Apr 16 18:05:08 +0000 2019,Ever wanted to master the art of the mulligan?...,107,10,39.1
74,Hearthstone,1209608880,Fri Apr 05 09:20:37 +0000 2019,Now live! It is time for another exclusive Ris...,107,10,39.1
75,Hearthstone,1209608880,Fri Apr 19 13:46:24 +0000 2019,RT @HSTopDecks: HCT World Championship 2019 is...,83,17,36.8
76,Hearthstone,1209608880,Fri Apr 26 01:58:58 +0000 2019,RT @HSesports: We're LIVE! The action continue...,80,18,36.6
77,Hearthstone,1209608880,Thu Apr 11 17:00:02 +0000 2019,Looking to update your look before entering th...,91,13,36.4
78,Hearthstone,1209608880,Mon Apr 22 16:47:36 +0000 2019,This kicks off in just a few minutes at 10 AM ...,95,11,36.2
79,Hearthstone,1209608880,Wed Apr 10 16:00:01 +0000 2019,Embrace the shadows and celebrate the launch o...,96,10,35.8
80,Hearthstone,1209608880,Tue Apr 16 21:54:01 +0000 2019,The final results for Hearthstone Ranked Stand...,97,9,35.4
81,Hearthstone,1209608880,Sat Apr 06 17:00:02 +0000 2019,This weekend you can visit a @MicrosoftStore t...,87,8,31.7
82,Hearthstone,1209608880,Tue Apr 09 17:21:47 +0000 2019,Learn more about everything coming to Hearthst...,89,7,31.6
83,Hearthstone,1209608880,Mon Apr 01 22:12:32 +0000 2019,RT @Blizzard_ANZ: The only thing better than s...,77,8,28.7
84,Hearthstone,1209608880,Thu Apr 18 18:05:10 +0000 2019,Creator @F2K_Slysssa dives into the current st...,78,7,28.3
85,Hearthstone,1209608880,Tue Apr 02 23:06:34 +0000 2019,"RT @TeamTespa: This weekend, our Tespa chapter...",57,13,26.2
86,Hearthstone,1209608880,Fri Mar 29 21:43:21 +0000 2019,A few more locations have been added to the li...,71,6,25.5
87,Hearthstone,1209608880,Thu Apr 18 13:55:29 +0000 2019,Apologies to @PathraCadness for our original p...,76,2,24.2
88,Hearthstone,1209608880,Mon Apr 22 18:00:08 +0000 2019,Can you handle the metal? Guitarist @HaarasNC ...,57,8,22.7
89,Hearthstone,1209608880,Sat Mar 30 19:49:52 +0000 2019,Unseen dangers lurk around every corner! #Rise...,56,5,20.3
90,Hearthstone,1209608880,Thu Mar 21 17:51:46 +0000 2019,"@Jack_SwallowHS Hey, Hex showing a cost of 3-m...",15,1,5.2
91,Hearthstone,1209608880,Fri Apr 12 18:18:24 +0000 2019,@DaveKosak @CONNOR_RAPPER https://t.co/Osr2YjQY0s,9,1,3.4
92,Hearthstone,1209608880,Fri Apr 05 09:42:51 +0000 2019,"@LeBruce We also have French, German, Spanish,...",4,2,2.6
93,Hearthstone,1209608880,Mon Apr 08 19:06:36 +0000 2019,@HS_Disq The Rise of Shadows pre-purchase bund...,1,1,1.0
94,Hearthstone,1209608880,Fri Apr 12 18:16:22 +0000 2019,@FlashsquidInk @bmkibler Us today. https://t.c...,3,0,0.9
95,Hearthstone,1209608880,Fri Apr 12 18:11:35 +0000 2019,@FlashsquidInk @bmkibler https://t.co/YMd0FSzqhw,2,0,0.6
96,Hearthstone,1209608880,Fri Apr 12 18:09:33 +0000 2019,@FlashsquidInk @bmkibler It's fire. Or evil? O...,2,0,0.6
97,Hearthstone,1209608880,Fri Apr 12 18:17:32 +0000 2019,@CONNOR_RAPPER Your rap is much appreciated by...,1,0,0.3
98,Hearthstone,1209608880,Tue Apr 09 17:24:35 +0000 2019,@tankyy10 You may need to log back out and bac...,1,0,0.3
99,Hearthstone,1209608880,Thu Mar 21 17:34:36 +0000 2019,"@AI_Mechanic Hey, Hex showing a cost of 3-mana...",1,0,0.3

In [15]:
sql="select avg(viralofpost) from (select (0.3*Favourites+0.7*retweets)as viralofpost from playhearthstone) as t"
sql_to_df(sql)

   avg(viralofpost)
0           159.741

Finally, I get the avg of viral of hearthstone homepage post. This result just show how viral of posts.

3.What posts are likely to be interesting to me?
First, I choose the screen_name do get his posts. Then use get what hashtags he uses, then use the hashtags to search what post does have the similar hashtags, then we get post that is like him.

In [16]:
sql="SELECT distinct hashtags,count(hashtags) as amount FROM project.playhearthstone group by hashtags order by amount desc"
sql_to_df(sql)

                  hashtags  amount
0                       []      52
1            RiseOfShadows      38
2                      HCT       5
3              Hearthstone       2
4  HearthstoneGrandmasters       2
5                  ハースストーン       1

we notice that RiseofShadows and HCT are the most two popular hashtags. Then we find whose post has the same hashtags in other table.

In [17]:
sql="select * from game where (post like '%RiseOfShadows%' or  post like'%HCT%')"
sql_to_df(sql)

,id,name,post,followers,created_at,retweet,favourites,statuses,hashtag
0,1121596459709870080,O Mago ✠,RT @Hearthpwn: #HCT World Championship 2019 Da...,12199,Fri Apr 26 02:06:48 +0000 2019,1,23943,63031,"[{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t..."
1,1121596368773107712,HearthPwn,#HCT World Championship 2019 Day 2 begins now!...,77754,Fri Apr 26 02:06:27 +0000 2019,1,9,7159,"[{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t..."
2,1120417608896065536,Sabs,(Hearthstone) Tempo Rogue Guide April 2019 | *...,76,Mon Apr 22 20:02:28 +0000 2019,0,2027,439,[{'text': 'RiseOfShadows'}]

4.What posts are like mine?
First, I choose the screen_name do get his posts,find which word is the most used. And, find the word in the post which posted by others. These post are like mine.

In [18]:
sql="SELECT word , COUNT(*) as total FROM ( SELECT  User_id  , SUBSTRING_INDEX(SUBSTRING_INDEX(Post,' ',2),' ',-1) as word  FROM playhearthstone ) as t GROUP BY word HAVING total >= 1 ORDER BY total DESC"
sql_to_df(sql)

                 word  total
0         @HSesports:      8
1                  to      7
2                 the      5
3                 you      5
4                Your      3
5              League      3
6           @bmkibler      3
7                  us      2
8               final      2
9                Hey,      2
10               some      2
11            weekend      2
12                few      2
13                 as      1
14  @Thats_TowelieHS:      1
15              track      1
16            forget,      1
17                  a      1
18           sinister      1
19              weave      1
20               will      1
21            veteran      1
22               evil      1
23        @TeamTespa:      1
24            dangers      1
25              never      1
26     @Blizzard_Ent:      1
27       @HSTopDecks:      1
28             wanted      1
29             you're      1
..                ...    ...
37       @DorianGorr:      1
38              where      1
39              live!      1
40             mayhem      1
41             forget      1
42          partnered      1
43     @SilentNickHS:      1
44               more      1
45             today,      1
46          @G2Thijs:      1
47          Defenders      1
48              maybe      1
49                 of      1
50               Now!      1
51                how      1
52               Boom      1
53        @DaveKosak:      1
54     @CONNOR_RAPPER      1
55  @PlayHearthstone:      1
56               14.0      1
57     @Blizzard_ANZ:      1
58               Lead      1
59              first      1
60              kicks      1
61              today      1
62           thrilled      1
63               Rise      1
64              Brian      1
65      @YukieTAJIMA:      1
66              gear?      1

[67 rows x 2 columns]

we can find that "@Hsesports" is the most used word.

In [19]:
sql="select * from game where post like '%esports%'"
sql_to_df(sql)

,id,name,post,followers,created_at,retweet,favourites,statuses,hashtag
0,1121659799467282432,Meli Marie ❤,RT @GhotiCzys: League of Legends Diana tee is ...,242,Fri Apr 26 06:18:30 +0000 2019,1,3465,699,"[{'text': 'lol'}, {'text': 'leagueoflegends'},..."
1,1121657606710259713,Jussi Halme,RT @esportsfinland: FELin Overwatch Cupin poti...,557,Fri Apr 26 06:09:47 +0000 2019,3,12403,5675,[]
2,1121596459709870080,O Mago ✠,RT @Hearthpwn: #HCT World Championship 2019 Da...,12199,Fri Apr 26 02:06:48 +0000 2019,1,23943,63031,"[{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t..."
3,1121596368773107712,HearthPwn,#HCT World Championship 2019 Day 2 begins now!...,77754,Fri Apr 26 02:06:27 +0000 2019,1,9,7159,"[{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t..."

5.What users post like me?
First, I choose the screen_name do get his posts,find which word is the most used. And, find the word in the post which posted by others. who post these post is the users who post like me.

In [20]:
sql="SELECT word , COUNT(*) as total FROM ( SELECT  User_id  , SUBSTRING_INDEX(SUBSTRING_INDEX(Post,' ',2),' ',-1) as word  FROM playhearthstone ) as t GROUP BY word HAVING total >= 1 ORDER BY total DESC"
sql_to_df(sql)

                 word  total
0         @HSesports:      8
1                  to      7
2                 the      5
3                 you      5
4                Your      3
5              League      3
6           @bmkibler      3
7                  us      2
8               final      2
9                Hey,      2
10               some      2
11            weekend      2
12                few      2
13                 as      1
14  @Thats_TowelieHS:      1
15              track      1
16            forget,      1
17                  a      1
18           sinister      1
19              weave      1
20               will      1
21            veteran      1
22               evil      1
23        @TeamTespa:      1
24            dangers      1
25              never      1
26     @Blizzard_Ent:      1
27       @HSTopDecks:      1
28             wanted      1
29             you're      1
..                ...    ...
37       @DorianGorr:      1
38              where      1
39              live!      1
40             mayhem      1
41             forget      1
42          partnered      1
43     @SilentNickHS:      1
44               more      1
45             today,      1
46          @G2Thijs:      1
47          Defenders      1
48              maybe      1
49                 of      1
50               Now!      1
51                how      1
52               Boom      1
53        @DaveKosak:      1
54     @CONNOR_RAPPER      1
55  @PlayHearthstone:      1
56               14.0      1
57     @Blizzard_ANZ:      1
58               Lead      1
59              first      1
60              kicks      1
61              today      1
62           thrilled      1
63               Rise      1
64              Brian      1
65      @YukieTAJIMA:      1
66              gear?      1

[67 rows x 2 columns]

In [21]:
sql="select id,post from game where post like '%esports%'"
sql_to_df(sql)

                    id                                               post
0  1121659799467282432  RT @GhotiCzys: League of Legends Diana tee is ...
1  1121657606710259713  RT @esportsfinland: FELin Overwatch Cupin poti...
2  1121596459709870080  RT @Hearthpwn: #HCT World Championship 2019 Da...
3  1121596368773107712  #HCT World Championship 2019 Day 2 begins now!...

6.Who should I be following?
I find some tags and search tags in game tweets to find other users Also I define popular person= 0.2 Fav + 0.2 Retweet+0.6followers 
then get the most popular person to follow.

In [22]:
sql="select name, (0.2*favourites +0.2*retweet+0.6*followers) As popularity from game order by popularity desc"
sql_to_df(sql)

                                        name  popularity
0                                  Overwatch   1952472.6
1                                  Overwatch   1952190.4
2                                   PC Gamer   1182446.6
3                               Apex Legends    631643.2
4                                    Wowhead    170264.0
5                                    Wowhead    170264.0
6                       San Francisco Shock⚡    100698.8
7                           Kenneth Hitchner     97202.8
8                            Niantic Support     92019.4
9                            Niantic Support     92019.4
10                           Niantic Support     92019.4
11                           Niantic Support     92019.4
12                              Daniel Peter     86048.8
13   Millenium : Esport / Jeux vidéo #GA2019     84317.4
14                             GamesIndustry     80603.0
15                          Stephen Courtney     73690.4
16                                たいりょう@霊夢提督     71908.4
17                               Warcraft_FR     66018.0
18                                   Bettman     63678.4
19                                 HearthPwn     46654.4
20                                 Zach Gage     44479.4
21                                   Krystal     40821.8
22                                        四季     36378.8
23                                        右端     32101.8
24                                Dave Kosak     30517.8
25                                Dave Kosak     30507.8
26                                     みっちゃん     25530.4
27                                     みっちゃん     25530.4
28                       scarlett ◟̽◞̽ ?️‍??     24813.2
29                                  Perculia     24193.0
..                                       ...         ...
432                           Edgar Aparicio        25.4
433                                 NIKATECH        23.0
434                                     nano        22.0
435                          Jennifer Lawson        20.4
436                                 Absolute        20.0
437                                 Absolute        20.0
438                                       みつ        16.4
439                                    ジュウソウ        15.8
440                             Anti Gravity        15.6
441                           SylveonLover05        15.4
442                                  the boy        14.0
443                                    ?????        13.8
444                                ゆいな@元鍵盤弾き        13.6
445                                   Joseph        11.6
446                            Pandan Social        10.8
447                         [ENGR]CLaNCh_kei         9.8
448                               Legionfarm         9.2
449                                   NiftyQ         9.2
450                                      n n         7.4
451                            Techtelegraph         7.2
452                                    Eyhze         6.6
453                               it's DEEZY         6.6
454                    That Feeling When Bot         5.6
455                               Bandy Gang         4.8
456                               Shneeki_TV         4.4
457                                     MLRB         2.8
458                                     ももたろ         2.2
459                            martin molina         2.2
460                                Leo Smith         1.6
461                                Leo Smith         1.6

[462 rows x 2 columns]

7.What topics are trending in my domain?
Collect hashtags from different three date,24,25,26.
Find which hashtags is trending

In [23]:
sql="SELECT hashtag,count(hashtag) as num FROM project.game where created_at like '%Apr 24%' group by hashtag order by num desc"
sql_to_df(sql)

                                             hashtag  num
0                                                 []   41
1  [{'text': 'Pokemon'}, {'text': 'children'}, {'...    2
2  [{'text': 'Win'}, {'text': 'Pokemon'}, {'text'...    2
3  [{'text': 'Hearthstone'}, {'text': 'Videogames...    2
4  [{'text': 'Games'}, {'text': 'Features'}, {'te...    1
5  [{'text': 'Pokemon'}, {'text': 'GameboyAdvance...    1
6                          [{'text': 'Hearthstone'}]    1

In [24]:
sql="SELECT hashtag,count(hashtag) as num FROM project.game where created_at like '%Apr 25%' group by hashtag order by num desc"
sql_to_df(sql)

                                             hashtag  num
0                                                 []   55
1                      [{'text': 'WorldofWarcraft'}]    3
2  [{'text': 'DarkmoonFaire'}, {'text': 'Warcraft'}]    2
3  [{'text': 'Melmetal'}, {'text': 'PokemonLetsGo...    2
4                             [{'text': 'Warcraft'}]    1
5  [{'text': 'Win'}, {'text': 'Pokemon'}, {'text'...    1
6    [{'text': 'hearthstone'}, {'text': 'giveaway'}]    1

In [25]:
sql="SELECT hashtag,count(hashtag) as num FROM project.game where created_at like '%Apr 26%' group by hashtag order by num desc"
sql_to_df(sql)

                                              hashtag  num
0                                                  []  144
1     [{'text': 'widowmaker'}, {'text': 'overwatch'}]   12
2                             [{'text': 'Overwatch'}]    5
3      [{'text': 'sadgamers'}, {'text': 'snackpack'}]    4
4   [{'text': 'Overwatch'}, {'text': 'OverwatchFan...    3
5                               [{'text': 'PS4live'}]    2
6   [{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t...    2
7   [{'text': 'ApexLegends'}, {'text': 'エーペックスレジェン...    2
8   [{'text': 'lol'}, {'text': 'leagueoflegends'},...    1
9         [{'text': 'Sombra'}, {'text': 'Overwatch'}]    1
10  [{'text': 'PS4share'}, {'text': 'APEX'}, {'tex...    1
11  [{'text': 'Brigitte'}, {'text': 'Widowmaker'},...    1
12                          [{'text': 'ApexLegends'}]    1
13  [{'text': 'ApexLegends'}, {'text': 'OctaneMain...    1
14         [{'text': 'Overwatch'}, {'text': 'Mercy'}]    1
15  [{'text': 'boombox'}, {'text': 'overwatch'}, {...    1
16                                 [{'text': 'Apex'}]    1
17  [{'text': 'ApexSeason1'}, {'text': 'APEXフレンド募集'}]    1
18         [{'text': 'overwatch'}, {'text': 'Moira'}]    1
19                              [{'text': 'GTSport'}]    1
20  [{'text': 'PS4live'}, {'text': 'Apex'}, {'text...    1
21                         [{'text': 'FREETHEBOOTY'}]    1
22  [{'text': 'German'}, {'text': 'Baptiste'}, {'t...    1
23                [{'text': 'ps4'}, {'text': 'apex'}]    1
24                          [{'text': 'FaceYourArt'}]    1
25                                [{'text': 'EDFIR'}]    1
26                                 [{'text': 'AE86'}]    1
27  [{'text': 'dVA'}, {'text': '오버워치'}, {'text': '...    1
28                          [{'text': 'SneakerHead'}]    1
29  [{'text': 'mercy'}, {'text': 'skin'}, {'text':...    1
30      [{'text': 'Overwatch'}, {'text': 'PS4share'}]    1
31               [{'text': 'News'}, {'text': 'blog'}]    1

We notice that hearthstone is popular in 24 and 26,but overwatch become the most popular in the latest data.

8.What keywords/ hashtags should I add to my post?
so this is the most choose what hashtags should add to my post , so I get his most popular tags, this easily to get count of tags from text.

In [26]:
sql="select hashtag,count(hashtag) as amount from game group by hashtag order by amount desc "
sql_to_df(sql)

                                              hashtag  amount
0                                                  []     355
1     [{'text': 'widowmaker'}, {'text': 'overwatch'}]      12
2                           [{'text': 'Hearthstone'}]      12
3                              [{'text': 'Warcraft'}]      10
4                             [{'text': 'Overwatch'}]       5
5   [{'text': 'Win'}, {'text': 'Pokemon'}, {'text'...       4
6      [{'text': 'sadgamers'}, {'text': 'snackpack'}]       4
7   [{'text': 'Overwatch'}, {'text': 'OverwatchFan...       3
8                       [{'text': 'WorldofWarcraft'}]       3
9   [{'text': 'Pokemon'}, {'text': 'children'}, {'...       3
10  [{'text': 'ApexLegends'}, {'text': 'エーペックスレジェン...       2
11  [{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t...       2
12  [{'text': 'DarkmoonFaire'}, {'text': 'Warcraft'}]       2
13               [{'text': 'News'}, {'text': 'blog'}]       2
14                              [{'text': 'PS4live'}]       2
15  [{'text': 'Melmetal'}, {'text': 'PokemonLetsGo...       2
16  [{'text': 'Hearthstone'}, {'text': 'Videogames...       2
17                     [{'text': 'BattleForAzeroth'}]       2
18                             [{'text': 'Warlocks'}]       1
19                [{'text': 'ps4'}, {'text': 'apex'}]       1
20                          [{'text': 'FaceYourArt'}]       1
21                                  [{'text': 'サンド'}]       1
22                                  [{'text': 'BFA'}]       1
23                                [{'text': 'EDFIR'}]       1
24                                 [{'text': 'AE86'}]       1
25  [{'text': 'dVA'}, {'text': '오버워치'}, {'text': '...       1
26  [{'text': 'Roleplay'}, {'text': 'Goblin'}, {'t...       1
27                          [{'text': 'SneakerHead'}]       1
28  [{'text': 'mercy'}, {'text': 'skin'}, {'text':...       1
29      [{'text': 'Overwatch'}, {'text': 'PS4share'}]       1
30    [{'text': 'hearthstone'}, {'text': 'giveaway'}]       1
31  [{'text': 'wowclassic'}, {'text': 'guide'}, {'...       1
32  [{'text': 'lol'}, {'text': 'leagueoflegends'},...       1
33        [{'text': 'Sombra'}, {'text': 'Overwatch'}]       1
34                             [{'text': 'underdog'}]       1
35  [{'text': 'PS4share'}, {'text': 'APEX'}, {'tex...       1
36  [{'text': 'Brigitte'}, {'text': 'Widowmaker'},...       1
37                          [{'text': 'ApexLegends'}]       1
38  [{'text': 'ApexLegends'}, {'text': 'OctaneMain...       1
39         [{'text': 'Overwatch'}, {'text': 'Mercy'}]       1
40  [{'text': 'boombox'}, {'text': 'overwatch'}, {...       1
41                        [{'text': 'RiseOfShadows'}]       1
42                                  [{'text': 'WoW'}]       1
43                                 [{'text': 'Apex'}]       1
44  [{'text': 'ApexSeason1'}, {'text': 'APEXフレンド募集'}]       1
45         [{'text': 'overwatch'}, {'text': 'Moira'}]       1
46  [{'text': 'Games'}, {'text': 'Features'}, {'te...       1
47                       [{'text': 'forthealliance'}]       1
48                              [{'text': 'GTSport'}]       1
49  [{'text': 'PS4live'}, {'text': 'Apex'}, {'text...       1
50                         [{'text': 'FREETHEBOOTY'}]       1
51  [{'text': 'German'}, {'text': 'Baptiste'}, {'t...       1
52  [{'text': 'Pokemon'}, {'text': 'GameboyAdvance...       1

Therefore, overwatch is the hashtag i should add to my post

9.Should I follow somebody back?
If the screen_name is following me. I want to define his popularity by 
popular person= 0.2 avg(Fav) + 0.2 (Retweet)+0.6followers
And, we decide that if the popularity greater than 50000, we should follow him back.

In [27]:
sql="SELECT name,(avg(Favourites)*0.2+avg(retweets)*0.2+avg(followers)*0.6) as popularity from playhearthstone group by name"
sql_to_df(sql)

          name  popularity
0  Hearthstone  526670.886

Therefore, we should follow him back.

10.What is the best time to post?
this question is to ask something about what time to post you can get more retweet and favs, so what I should do is filter the similar post which have same hashtags. Then sorting them by favs and retweet. this I should define the best time to post is 0.5*favs+0.5retweets

In [28]:
sql="select created_at ,(0.5*Favourites+0.5*retweet) as timepost from game order by timepost desc"
sql_to_df(sql)

                         created_at  timepost
0    Fri Apr 19 18:06:05 +0000 2019  195677.5
1    Fri Apr 26 06:16:31 +0000 2019  169133.0
2    Tue Apr 23 09:09:15 +0000 2019  158477.5
3    Fri Apr 26 06:16:37 +0000 2019  134957.0
4    Fri Apr 26 06:12:50 +0000 2019   88812.5
5    Fri Apr 26 06:14:32 +0000 2019   78645.0
6    Thu Apr 25 11:49:35 +0000 2019   60099.5
7    Fri Apr 26 06:14:40 +0000 2019   58942.0
8    Fri Apr 26 06:14:37 +0000 2019   58942.0
9    Thu Apr 25 10:20:10 +0000 2019   55959.0
10   Fri Apr 26 06:11:57 +0000 2019   49181.5
11   Thu Apr 25 05:40:43 +0000 2019   46382.5
12   Tue Apr 23 19:05:29 +0000 2019   46096.5
13   Mon Apr 22 09:30:41 +0000 2019   44983.5
14   Fri Apr 26 06:15:37 +0000 2019   43362.5
15   Mon Apr 22 08:34:06 +0000 2019   43351.0
16   Fri Apr 26 06:12:46 +0000 2019   42440.5
17   Fri Apr 19 20:33:39 +0000 2019   40645.5
18   Fri Apr 26 06:12:56 +0000 2019   40274.0
19   Thu Apr 25 05:33:06 +0000 2019   38067.0
20   Thu Apr 25 05:56:52 +0000 2019   33963.5
21   Tue Apr 23 18:31:19 +0000 2019   33548.5
22   Fri Apr 26 06:13:25 +0000 2019   33538.5
23   Mon Apr 22 21:49:24 +0000 2019   33518.5
24   Wed Apr 24 15:50:43 +0000 2019   32806.0
25   Fri Apr 26 06:14:09 +0000 2019   32575.5
26   Fri Apr 19 16:47:01 +0000 2019   31719.0
27   Fri Apr 26 06:09:33 +0000 2019   31095.5
28   Fri Apr 26 06:13:32 +0000 2019   29168.5
29   Fri Apr 26 06:18:34 +0000 2019   26932.0
..                              ...       ...
432  Fri Apr 26 06:14:29 +0000 2019       0.5
433  Fri Apr 26 06:14:04 +0000 2019       0.5
434  Fri Apr 26 06:19:00 +0000 2019       0.5
435  Fri Apr 26 06:15:08 +0000 2019       0.5
436  Fri Apr 26 06:13:42 +0000 2019       0.5
437  Fri Apr 26 06:12:45 +0000 2019       0.5
438  Fri Apr 26 06:12:21 +0000 2019       0.5
439  Fri Apr 26 06:10:10 +0000 2019       0.5
440  Fri Apr 26 06:09:55 +0000 2019       0.5
441  Fri Apr 26 06:09:27 +0000 2019       0.5
442  Thu Apr 25 22:26:55 +0000 2019       0.5
443  Thu Apr 25 08:25:36 +0000 2019       0.5
444  Wed Apr 24 19:06:47 +0000 2019       0.5
445  Wed Apr 24 09:17:02 +0000 2019       0.5
446  Tue Apr 23 20:14:56 +0000 2019       0.5
447  Wed Apr 24 09:40:19 +0000 2019       0.5
448  Sat Apr 20 17:53:07 +0000 2019       0.5
449  Thu Apr 25 09:53:26 +0000 2019       0.0
450  Wed Apr 24 21:24:32 +0000 2019       0.0
451  Sat Apr 20 00:39:34 +0000 2019       0.0
452  Fri Apr 19 18:06:41 +0000 2019       0.0
453  Fri Apr 26 06:09:30 +0000 2019       0.0
454  Fri Apr 26 00:08:58 +0000 2019       0.0
455  Thu Apr 25 22:37:04 +0000 2019       0.0
456  Thu Apr 25 22:23:09 +0000 2019       0.0
457  Thu Apr 25 22:22:14 +0000 2019       0.0
458  Wed Apr 24 01:06:10 +0000 2019       0.0
459  Tue Apr 23 20:23:34 +0000 2019       0.0
460  Tue Apr 23 20:17:17 +0000 2019       0.0
461  Tue Apr 23 20:14:56 +0000 2019       0.0

[462 rows x 2 columns]

Therefore,18:06 is the best time to post.

# 4 views and 4 functions

function 1:
CREATE DEFINER=`root`@`localhost` FUNCTION `compare`(id1 int,id2 int) RETURNS int(11)
    READS SQL DATA
BEGIN
declare a int;
declare b int;
select followers into a from game where id=id1;
select followers into b from game where id=id2;
if a > b
 then
 return id1;
else
 return id2;
 end if;

END
#input two id ,compare their followers and return the larger one

In [29]:
sql="select created_at ,(0.5*Favourites+0.5*retweet) as timepost from game order by timepost desc"
sql_to_df(sql)

                         created_at  timepost
0    Fri Apr 19 18:06:05 +0000 2019  195677.5
1    Fri Apr 26 06:16:31 +0000 2019  169133.0
2    Tue Apr 23 09:09:15 +0000 2019  158477.5
3    Fri Apr 26 06:16:37 +0000 2019  134957.0
4    Fri Apr 26 06:12:50 +0000 2019   88812.5
5    Fri Apr 26 06:14:32 +0000 2019   78645.0
6    Thu Apr 25 11:49:35 +0000 2019   60099.5
7    Fri Apr 26 06:14:40 +0000 2019   58942.0
8    Fri Apr 26 06:14:37 +0000 2019   58942.0
9    Thu Apr 25 10:20:10 +0000 2019   55959.0
10   Fri Apr 26 06:11:57 +0000 2019   49181.5
11   Thu Apr 25 05:40:43 +0000 2019   46382.5
12   Tue Apr 23 19:05:29 +0000 2019   46096.5
13   Mon Apr 22 09:30:41 +0000 2019   44983.5
14   Fri Apr 26 06:15:37 +0000 2019   43362.5
15   Mon Apr 22 08:34:06 +0000 2019   43351.0
16   Fri Apr 26 06:12:46 +0000 2019   42440.5
17   Fri Apr 19 20:33:39 +0000 2019   40645.5
18   Fri Apr 26 06:12:56 +0000 2019   40274.0
19   Thu Apr 25 05:33:06 +0000 2019   38067.0
20   Thu Apr 25 05:56:52 +0000 2019   33963.5
21   Tue Apr 23 18:31:19 +0000 2019   33548.5
22   Fri Apr 26 06:13:25 +0000 2019   33538.5
23   Mon Apr 22 21:49:24 +0000 2019   33518.5
24   Wed Apr 24 15:50:43 +0000 2019   32806.0
25   Fri Apr 26 06:14:09 +0000 2019   32575.5
26   Fri Apr 19 16:47:01 +0000 2019   31719.0
27   Fri Apr 26 06:09:33 +0000 2019   31095.5
28   Fri Apr 26 06:13:32 +0000 2019   29168.5
29   Fri Apr 26 06:18:34 +0000 2019   26932.0
..                              ...       ...
432  Fri Apr 26 06:14:29 +0000 2019       0.5
433  Fri Apr 26 06:14:04 +0000 2019       0.5
434  Fri Apr 26 06:19:00 +0000 2019       0.5
435  Fri Apr 26 06:15:08 +0000 2019       0.5
436  Fri Apr 26 06:13:42 +0000 2019       0.5
437  Fri Apr 26 06:12:45 +0000 2019       0.5
438  Fri Apr 26 06:12:21 +0000 2019       0.5
439  Fri Apr 26 06:10:10 +0000 2019       0.5
440  Fri Apr 26 06:09:55 +0000 2019       0.5
441  Fri Apr 26 06:09:27 +0000 2019       0.5
442  Thu Apr 25 22:26:55 +0000 2019       0.5
443  Thu Apr 25 08:25:36 +0000 2019       0.5
444  Wed Apr 24 19:06:47 +0000 2019       0.5
445  Wed Apr 24 09:17:02 +0000 2019       0.5
446  Tue Apr 23 20:14:56 +0000 2019       0.5
447  Wed Apr 24 09:40:19 +0000 2019       0.5
448  Sat Apr 20 17:53:07 +0000 2019       0.5
449  Thu Apr 25 09:53:26 +0000 2019       0.0
450  Wed Apr 24 21:24:32 +0000 2019       0.0
451  Sat Apr 20 00:39:34 +0000 2019       0.0
452  Fri Apr 19 18:06:41 +0000 2019       0.0
453  Fri Apr 26 06:09:30 +0000 2019       0.0
454  Fri Apr 26 00:08:58 +0000 2019       0.0
455  Thu Apr 25 22:37:04 +0000 2019       0.0
456  Thu Apr 25 22:23:09 +0000 2019       0.0
457  Thu Apr 25 22:22:14 +0000 2019       0.0
458  Wed Apr 24 01:06:10 +0000 2019       0.0
459  Tue Apr 23 20:23:34 +0000 2019       0.0
460  Tue Apr 23 20:17:17 +0000 2019       0.0
461  Tue Apr 23 20:14:56 +0000 2019       0.0

[462 rows x 2 columns]

function 2 :
CREATE DEFINER=`root`@`localhost` FUNCTION `favLevel`(p_favLimit double) RETURNS varchar(10) CHARSET utf8mb4
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE lvl varchar(10);
 
    IF p_favLimit > 500 THEN
 SET lvl = '1';
    ELSEIF (p_favLimit <= 500 AND p_favLimit >= 100) THEN
        SET lvl = '2';
    ELSEIF p_favLimit < 100 THEN
        SET lvl = '3';
    END IF;
 
 RETURN (lvl);
END
#identify the level of favourites for the input favourites

In [32]:
sql="select id,favLevel(favourites) from game order by id"
sql_to_df(sql)

                      id favLevel(favourites)
0    1118196681269493762                    3
1    1118227068381270016                    1
2    1118228508457746438                    1
3    1118287985794002945                    2
4    1118294222002638848                    1
5    1118350324366893057                    1
6    1118405727289257984                    1
7    1118519683056058368                    3
8    1118847726828040192                    1
9    1118898870510137344                    3
10   1118930538562117632                    3
11   1118931858488745988                    2
12   1118958071106232320                    2
13   1118991166756786185                    1
14   1118992480404496385                    3
15   1119257227255328768                    1
16   1119279501102522369                    3
17   1119279665296945152                    1
18   1119281256464887808                    1
19   1119282722881593344                    1
20   1119289469318893569                    2
21   1119289470916923392                    3
22   1119301155790524416                    1
23   1119301304705331200                    3
24   1119302806907887616                    3
25   1119307537659105280                    3
26   1119309428820332545                    3
27   1119309897273712640                    1
28   1119318527779852288                    3
29   1119322667536961536                    3
..                   ...                  ...
432  1121659259047907330                    1
433  1121659265825955843                    1
434  1121659281336455170                    1
435  1121659287476957188                    1
436  1121659300915507202                    1
437  1121659301557198848                    1
438  1121659304803627008                    1
439  1121659323359219712                    1
440  1121659327972950019                    1
441  1121659335908528128                    1
442  1121659353428193282                    1
443  1121659355642773514                    1
444  1121659358230630400                    2
445  1121659373095284737                    1
446  1121659374714273794                    1
447  1121659386328309761                    1
448  1121659386655412225                    1
449  1121659397392875521                    1
450  1121659411993202688                    1
451  1121659471057436672                    1
452  1121659496122609664                    3
453  1121659520978079744                    3
454  1121659573033508864                    1
455  1121659649185292288                    2
456  1121659720358457344                    1
457  1121659769557639169                    1
458  1121659783696637952                    1
459  1121659799467282432                    1
460  1121659815963418624                    1
461  1121659928270135300                    3

[462 rows x 2 columns]

function 3:
CREATE DEFINER=`root`@`localhost` FUNCTION `iffamous`(wid int) RETURNS varchar(20) CHARSET utf8
    READS SQL DATA
BEGIN
 declare a nvarchar(20);
 declare b int; 
 select Favourites into b from game where id=wid;
 if b > 500
  then
  set a = 'famous';
 else
  set a= 'notfamous'; 
  end if;
RETURN a;
END
#input id and return if it is famous

In [33]:
sql="select iffamous('1118519683056058368')"
sql_to_df(sql)

/anaconda3/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)
/anaconda3/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (3720, 'NATIONAL/NCHAR/NVARCHAR implies the character set UTF8MB3, which will be replaced by UTF8MB4 in a future release. Please consider using CHAR(x) CHARACTER SET UTF8MB4 in order to be unambiguous.')
  result = self._query(query)

  iffamous('1118519683056058368')
0                       notfamous

function 4:
CREATE DEFINER=`root`@`localhost` FUNCTION `get_time`(tLimit double) RETURNS varchar(10) CHARSET utf8mb4
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE lvl text;
    IF tLimit > 2010 THEN
        SET lvl = 'new';
    ELSEIF (tLimit <= 2010 AND tLimit >= 2000) THEN
        SET lvl = 'regular';
    ELSEIF tLimit < 2000 THEN
        SET lvl = 'old';
    END IF;
 
 RETURN (lvl);
END
#input the year of release,and indentify it is new or old

In [36]:
sql="select name,get_time(Year_of_Release) from video_games_sales"
sql_to_df(sql)

,name,get_time(Year_of_Release)
0,Wii Sports,regular
1,Super Mario Bros.,old
2,Mario Kart Wii,regular
3,Wii Sports Resort,regular
4,Pokemon Red/Pokemon Blue,old
5,Tetris,old
6,New Super Mario Bros.,regular
7,Wii Play,regular
8,New Super Mario Bros. Wii,regular
9,Duck Hunt,old
10,Nintendogs,regular
11,Mario Kart DS,regular
12,Pokemon Gold/Pokemon Silver,old
13,Wii Fit,regular
14,Kinect Adventures!,regular
15,Wii Fit Plus,regular
16,Grand Theft Auto V,new
17,Grand Theft Auto: San Andreas,regular
18,Super Mario World,old
19,Brain Age: Train Your Brain in Minutes a Day,regular
20,Pokemon Diamond/Pokemon Pearl,regular
21,Super Mario Land,old
22,Super Mario Bros. 3,old
23,Grand Theft Auto V,new
24,Grand Theft Auto: Vice City,regular
25,Pokemon Ruby/Pokemon Sapphire,regular
26,Brain Age 2: More Training in Minutes a Day,regular
27,Pokemon Black/Pokemon White,regular
28,Gran Turismo 3: A-Spec,regular
29,Call of Duty: Modern Warfare 3,new
...,...,...
16420,Help Wanted: 50 Wacky Jobs (jp sales),regular
16421,Yattaman Wii: BikkuriDokkiri Machine de Mou Ra...,regular
16422,Neo Angelique Special,regular
16423,Outdoors Unleashed: Africa 3D,new
16424,Real Rode,regular
16425,Pony Friends 2,regular
16426,Dynasty Warriors: Eiketsuden,new
16427,Metal Gear Solid V: Ground Zeroes,new
16428,PGA European Tour,regular
16429,Carmageddon 64,old
16430,Planet Monsters,regular
16431,Breach,new
16432,Bust-A-Move 3000,regular
16433,Mega Brain Boost,regular
16434,The Longest 5 Minutes,new
16435,Mezase!! Tsuri Master DS,regular
16436,Eiyuu Densetsu: Sora no Kiseki Material Collec...,regular
16437,STORM: Frontline Nation,new
16438,Strawberry Nauts,new
16439,Plushees,regular
16440,15 Days,regular
16441,Men in Black II: Alien Escape,regular
16442,Aiyoku no Eustia,new
16443,Woody Woodpecker in Crazy Castle 5,regular
16444,SCORE International Baja 1000: The Official Game,regular
16445,Samurai Warriors: Sanada Maru,new
16446,LMA Manager 2007,regular
16447,Haitaka no Psychedelica,new
16448,Spirits & Spells,regular
16449,Winning Post 8 2016,new

1.views:
CREATE VIEW firstview AS
SELECT *
FROM game
WHERE favourites >500;

In [37]:
sql="SELECT * FROM project.firstview;"
sql_to_df(sql)

,id,name,post,followers,created_at,retweet,favourites,statuses,hashtag
0,1121485262385754112,Katia,RT @BreakflipFR: Le progress de Battle for Aze...,16,Thu Apr 25 18:44:57 +0000 2019,2,6264,5960,[{'text': 'WorldofWarcraft'}]
1,1121461931338944512,Alex Gwartney,RT @Meraki22: Just in case you missed it! Dark...,306,Thu Apr 25 17:12:14 +0000 2019,1,2687,3846,"[{'text': 'DarkmoonFaire'}, {'text': 'Warcraft'}]"
2,1121446893425430528,Meraki22,Just in case you missed it! Darkmoon Faire: Qu...,416,Thu Apr 25 16:12:29 +0000 2019,1,5425,4038,"[{'text': 'DarkmoonFaire'}, {'text': 'Warcraft'}]"
3,1121385703240294400,Volkatz,RT @BreakflipFR: Le progress de Battle for Aze...,141,Thu Apr 25 12:09:20 +0000 2019,2,8578,4318,[{'text': 'WorldofWarcraft'}]
4,1121288585884209153,FTWitachi,? THE *ELEVENTH HOUR* GAMING SHOW | NOBLEGARDE...,1202,Thu Apr 25 05:43:26 +0000 2019,0,16856,54152,[]
5,1120771457179631616,Katia,RT @BreakflipFR: La version mythique du Creuse...,16,Tue Apr 23 19:28:32 +0000 2019,1,6264,5960,[{'text': 'BattleForAzeroth'}]
6,1120716670782382081,Deltrax,RT @wowisclassic_Fr: WoW Classic arrive bientô...,13,Tue Apr 23 15:50:50 +0000 2019,16,2252,2266,[]
7,1120615606309609477,Bettman,RT @Vanioon: Dieses Jahr mit ein paar neuen Be...,479,Tue Apr 23 09:09:15 +0000 2019,3,316952,61010,[]
8,1120613607060930560,"Abby ?⏸ , Morgenzombie",RT @Vanioon: Dieses Jahr mit ein paar neuen Be...,161,Tue Apr 23 09:01:18 +0000 2019,3,12934,6942,[]
9,1120609624477057029,DonBaron,RT @Vanioon: Dieses Jahr mit ein paar neuen Be...,75,Tue Apr 23 08:45:29 +0000 2019,3,18417,5243,[]
10,1120540124218044416,PlayerAuctions,"This WoW Engineering guide covers a chunk, inc...",6689,Tue Apr 23 04:09:18 +0000 2019,0,821,4722,[]
11,1120466689215410178,Mementh,"RT @WarcraftSecrets: Luckily for us, Levantus ...",429,Mon Apr 22 23:17:30 +0000 2019,2,25734,844691,[]
12,1120461722119278594,thewayitis35,"RT @WarcraftSecrets: Luckily for us, Levantus ...",673,Mon Apr 22 22:57:46 +0000 2019,2,40176,31638,[]
13,1120377208172711938,りーだくまー?1130,RT @WarcraftSecrets: The Noblegarden World Eve...,332,Mon Apr 22 17:21:56 +0000 2019,1,27921,151854,[]
14,1120333042441183232,catcat,RT @BlizzSpirit: L'événement mondial du Jardin...,686,Mon Apr 22 14:26:26 +0000 2019,1,37079,19392,[]
15,1120236836905996289,Les pions sur les i,RT @JudgeHype: Guide de l'événement : Jardin d...,612,Mon Apr 22 08:04:09 +0000 2019,2,19483,4851,[{'text': 'Warcraft'}]
16,1120127857580236802,Marcos Guedes,@ericbraddock @Warcraft @pcgamer We still mour...,177,Mon Apr 22 00:51:06 +0000 2019,0,6087,2616,[{'text': 'forthealliance'}]
17,1119962599167283202,Blais0u,RT @wowisclassic_Fr: WoW Classic arrive bientô...,108,Sun Apr 21 13:54:26 +0000 2019,16,586,2048,[]
18,1119653249919934465,Mitriarche,RT @wowisclassic_Fr: WoW Classic arrive bientô...,15,Sat Apr 20 17:25:11 +0000 2019,16,512,837,[]
19,1119631231589785600,Secondcoming,@Flip_x3 @Nano_Warcraft @CadenHouse Did that g...,13,Sat Apr 20 15:57:42 +0000 2019,0,4200,227,[]
20,1119628814299086855,Guy G.,RT @wowisclassic_Fr: WoW Classic arrive bientô...,151,Sat Apr 20 15:48:05 +0000 2019,16,5118,2986,[]
21,1119301155790524416,Kenneth Hitchner,World of Warcraft: Battle for Azeroth allied r...,31553,Fri Apr 19 18:06:05 +0000 2019,0,391355,135907,[]
22,1118991166756786185,James Twyford,"Wow, what? An actual Blizzard-produced page in...",161,Thu Apr 18 21:34:18 +0000 2019,0,1005,3739,[]
23,1118847726828040192,Meraki22,Did you catch this? From The Ground Up: Goblin...,416,Thu Apr 18 12:04:19 +0000 2019,0,5425,4038,"[{'text': 'Roleplay'}, {'text': 'Goblin'}, {'t..."
24,1118405727289257984,Warcraft_FR,RT @TontonTwitch: Today c'est WoW!\n\n**On fai...,109577,Wed Apr 17 06:47:59 +0000 2019,3,1356,7343,[]
25,1118350324366893057,Danielle?,RT @chyronsmaiden: My incredibly patient warcr...,403,Wed Apr 17 03:07:49 +0000 2019,1,4952,1658,[]
26,1118294222002638848,Gwendlyn Drayton,RT @AndromaxeMaes: Find your inner light to gu...,1235,Tue Apr 16 23:24:54 +0000 2019,2,33799,13056,[{'text': 'Warcraft'}]
27,1118228508457746438,enzo,RT @wowisclassic_Fr: WoW Classic arrive bientô...,31,Tue Apr 16 19:03:46 +0000 2019,16,2575,2688,[]
28,1118227068381270016,Katia,RT @BreakflipFR: Quelles stratégies adoptées p...,16,Tue Apr 16 18:58:03 +0000 2019,1,6264,5960,[]
29,1121468058856349696,Apex Legends,"Gather round, Legends. We've got an update fro...",1049076,Thu Apr 25 17:36:35 +0000 2019,1456,9532,428,[]
...,...,...,...,...,...,...,...,...,...
260,1120348093839360000,Krystal,RT @Wowhead: Noblegarden is here on EU realms!...,65455,Mon Apr 22 15:26:15 +0000 2019,30,7714,62744,[]
261,1120340854680379398,Malasteren,RT @Wowhead: Noblegarden is here on EU realms!...,99,Mon Apr 22 14:57:29 +0000 2019,30,10995,4946,[]
262,1120327594459709441,Tok,guys join the stream to have a chance get free...,1008,Mon Apr 22 14:04:47 +0000 2019,0,658,2182,[{'text': 'hearthstone'}]
263,1120313706607337472,☕ Meileo ☕,RT @Wowhead: Noblegarden is here on EU realms!...,1483,Mon Apr 22 13:09:36 +0000 2019,30,51640,45855,[]
264,1120309055245959168,Arashi PoW,RT @Wowhead: Noblegarden is here on EU realms!...,1292,Mon Apr 22 12:51:07 +0000 2019,30,18239,19518,[]
265,1120300245236310021,?Citrus The Corgi ? ➡ @canFURence 2019,RT @Wowhead: Noblegarden is here on EU realms!...,472,Mon Apr 22 12:16:07 +0000 2019,30,3712,951,[]
266,1120287822647193600,?[?] Georgia/Senpai Nines~ [⚠️KHUX⚠️ID: 1540796],RT @Wowhead: Noblegarden is here on EU realms!...,124,Mon Apr 22 11:26:45 +0000 2019,30,10320,12188,[]
267,1120287515817148417,Flower Crowned Hunter,RT @Wowhead: Noblegarden is here on EU realms!...,261,Mon Apr 22 11:25:32 +0000 2019,30,10244,5296,[]
268,1120281448366448640,Afra ?,RT @Wowhead: Noblegarden is here on EU realms!...,15404,Mon Apr 22 11:01:25 +0000 2019,30,23420,48517,[]
269,1120266546495070208,Roka,RT @Wowhead: Noblegarden is here on EU realms!...,21,Mon Apr 22 10:02:12 +0000 2019,30,4122,1336,[]
270,1120258614088929281,Loa of Chronic Pain,RT @Wowhead: Noblegarden is here on EU realms!...,1394,Mon Apr 22 09:30:41 +0000 2019,30,89937,45701,[]
271,1120246409653960704,빛벼림 ATM,RT @Wowhead: Noblegarden is here on EU realms!...,157,Mon Apr 22 08:42:11 +0000 2019,30,15557,91980,[]
272,1120246164899729409,Mementh,RT @Wowhead: Noblegarden is here on EU realms!...,429,Mon Apr 22 08:41:13 +0000 2019,30,25734,844691,[]
273,1120244373197860864,For The Horde,RT @Wowhead: Noblegarden is here on EU realms!...,3291,Mon Apr 22 08:34:06 +0000 2019,30,86672,15062,[]
274,1120243709138747397,LABOYS,RT @Wowhead: Noblegarden is here on EU realms!...,80,Mon Apr 22 08:31:28 +0000 2019,30,13384,8298,[]
275,1120242378390921216,Aisycle,@shink_hikari 自分は割と感覚的にプレイしてるのであんまり役に立たないですけど、...,425,Mon Apr 22 08:26:10 +0000 2019,0,2584,32332,[]
276,1120241367706370048,Ksane-кишковёрт,RT @Wowhead: Noblegarden is here on EU realms!...,338,Mon Apr 22 08:22:09 +0000 2019,30,14550,27893,[]
277,1120030094720999425,Simeon AstraLa,KRIPP’S CRAFTING GUIDE - Rise of Shadows Heart...,242,Sun Apr 21 18:22:38 +0000 2019,0,33468,7963,[]
278,1119752654861692928,HearthStarter,RT @Old_GuardianHS: 70% winrate Legend Bomb Hu...,441,Sun Apr 21 00:00:11 +0000 2019,1,6335,4995,[]
279,1119729457789636610,Gunnolf Bjorn,I've been working on a new aggro mech mage lis...,256,Sat Apr 20 22:28:00 +0000 2019,0,2419,1459,[]
280,1119636461387538433,Eddie,@pwtenny if you ever need or want someone that...,199,Sat Apr 20 16:18:28 +0000 2019,0,18858,33507,[]
281,1119617807400960000,Tok,RT @Fluxflashor: A wild Rise of Shadows Pack G...,1008,Sat Apr 20 15:04:21 +0000 2019,81,658,2182,[]
282,1119524360270897152,Gangretik,RT @M_TCG_FR: En galère d'idées de decks ? On ...,75,Sat Apr 20 08:53:01 +0000 2019,4,2013,2854,[]
283,1119385447535456256,Stelios Magoutis,"RT @HSTopDecks: If you don't like Murlocs, the...",69,Fri Apr 19 23:41:02 +0000 2019,1,3734,1943,[]
284,1119338289457246209,HyakuZero,RT @M_TCG_FR: En galère d'idées de decks ? On ...,96,Fri Apr 19 20:33:39 +0000 2019,4,81287,21218,[]
285,1119309897273712640,猫掌打?,RT @neon31HS: Hearthstone Malygos Rogue #456 L...,1286,Fri Apr 19 18:40:49 +0000 2019,2,24891,5729,[]
286,1119282722881593344,inconnu aubataillon,RT @M_TCG_FR: En galère d'idées de decks ? On ...,14,Fri Apr 19 16:52:51 +0000 2019,4,2592,1066,[]
287,1119281256464887808,The Loss Soldier's⚔️♠️,RT @pcgamer: Beat those pesky Bomb Warriors wi...,397,Fri Apr 19 16:47:01 +0000 2019,1,63437,157350,[]
288,1119279665296945152,Julietta Carson,RT pcgamer: Beat those pesky Bomb Warriors wit...,1291,Fri Apr 19 16:40:42 +0000 2019,0,3411,9053,[]
289,1119257227255328768,Millenium : Esport / Jeux vidéo #GA2019,RT @M_TCG_FR: En galère d'idées de decks ? On ...,138450,Fri Apr 19 15:11:32 +0000 2019,4,6233,48275,[]

2.create VIEW `secondview` AS
    SELECT 
        `video_games_sales`.`Name` AS `Name`,
        `video_games_sales`.`Platform` AS `Platform`,
        `video_games_sales`.`Year_of_Release` AS `Year_of_Release`,
        `video_games_sales`.`Genre` AS `Genre`,
        `video_games_sales`.`Publisher` AS `Publisher`,
        `video_games_sales`.`NA_Sales` AS `NA_Sales`,
        `video_games_sales`.`EU_Sales` AS `EU_Sales`,
        `video_games_sales`.`JP_Sales` AS `JP_Sales`,
        `video_games_sales`.`Other_Sales` AS `Other_Sales`,
        `video_games_sales`.`Global_Sales` AS `Global_Sales`,
        `video_games_sales`.`Critic_Score` AS `Critic_Score`,
        `video_games_sales`.`Critic_Count` AS `Critic_Count`,
        `video_games_sales`.`User_Score` AS `User_Score`,
        `video_games_sales`.`User_Count` AS `User_Count`,
        `video_games_sales`.`Developer` AS `Developer`,
        `video_games_sales`.`Rating` AS `Rating`
    FROM
        `video_games_sales`
    WHERE
        ((`video_games_sales`.`Global_Sales` > 50)
            AND (`video_games_sales`.`Year_of_Release` > 1999))

In [38]:
sql="SELECT * FROM project.secondview;"
sql_to_df(sql)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76,51,8,322,Nintendo,E

3.
CREATE VIEW `thirdview` AS
SELECT name,User_id,Posted_time,post,Favourites,retweets,(0.3*Favourites+0.7*retweets) as viralofmypost 
FROM project.playhearthstone 
order by viralofmypost desc

In [39]:
sql="SELECT * FROM project.thirdview;"
sql_to_df(sql)

,name,User_id,Posted_time,post,Favourites,retweets,viralofmypost
0,Hearthstone,1209608880,Wed Mar 27 22:59:07 +0000 2019,RT @YukieTAJIMA: 【Hearthstone】今年もあの日が近づいてきました\...,6670,2324,3627.8
1,Hearthstone,1209608880,Thu Apr 25 14:24:45 +0000 2019,RT @Blizzard_Ent: BlizzCon 2019 will be Novemb...,3459,803,1599.8
2,Hearthstone,1209608880,Thu Apr 25 02:19:24 +0000 2019,"Win or lose, Stonebrew’s Tavern is a place to ...",3167,780,1496.1
3,Hearthstone,1209608880,Mon Apr 08 19:42:27 +0000 2019,We’re thrilled to announce that tomorrow’s rel...,1472,312,660.0
4,Hearthstone,1209608880,Thu Apr 25 07:01:11 +0000 2019,"RT @HSesports: ✨ And just like that, we're in ...",1161,152,454.7
5,Hearthstone,1209608880,Thu Apr 04 21:30:01 +0000 2019,"Starting today, login on either iOS, Android, ...",801,189,372.6
6,Hearthstone,1209608880,Fri Mar 22 17:00:24 +0000 2019,"What will Madame Lazul find,\nwhen she gazes i...",887,138,362.7
7,Hearthstone,1209608880,Wed Mar 27 00:08:36 +0000 2019,RT @DekkiGamesJP: 【新カード独占公開】ゲームコミュニティDEKKIは #ハ...,473,246,314.1
8,Hearthstone,1209608880,Tue Apr 09 17:09:49 +0000 2019,"The League of E.V.I.L. has assembled, their ta...",629,94,254.5
9,Hearthstone,1209608880,Wed Apr 17 09:31:30 +0000 2019,RT @Thats_TowelieHS: @PlayHearthstone 'Member ...,651,69,243.6
10,Hearthstone,1209608880,Thu Apr 04 14:00:08 +0000 2019,The Rise of Shadows card reveals have been com...,550,65,210.5
11,Hearthstone,1209608880,Wed Mar 20 20:09:06 +0000 2019,Join us for our first #RiseOfShadows card reve...,521,71,206.0
12,Hearthstone,1209608880,Tue Apr 02 17:00:33 +0000 2019,Watch some of your favorite streamers craft de...,557,51,202.8
13,Hearthstone,1209608880,Thu Apr 04 19:00:02 +0000 2019,"Login to claim Archmage Vargoth, for free! Thi...",437,85,190.6
14,Hearthstone,1209608880,Mon Apr 01 18:01:02 +0000 2019,"Join Brian Kibler, Senior Hearthstone Designer...",425,67,174.4
15,Hearthstone,1209608880,Tue Mar 26 20:00:01 +0000 2019,Don't forget to login between now and April 2 ...,393,70,166.9
16,Hearthstone,1209608880,Tue Apr 16 12:27:03 +0000 2019,RT @DorianGorr: @PlayHearthstone When Khadgar ...,439,43,161.8
17,Hearthstone,1209608880,Wed Apr 17 23:54:17 +0000 2019,RT @DaveKosak: Okay #Hearthstone villains and ...,447,39,161.4
18,Hearthstone,1209608880,Tue Apr 23 15:54:26 +0000 2019,RT @HSesports: Twitch Drops are inbound for th...,346,72,154.2
19,Hearthstone,1209608880,Wed Apr 03 20:32:11 +0000 2019,Take a look at every card coming to Hearthston...,332,70,148.6
20,Hearthstone,1209608880,Mon Apr 08 21:21:52 +0000 2019,RT @PlayHearthstone: Something evil is assured...,326,52,134.2
21,Hearthstone,1209608880,Fri Apr 05 17:01:00 +0000 2019,"Something evil is assuredly afoot, and it has ...",326,52,134.2
22,Hearthstone,1209608880,Tue Apr 02 14:55:29 +0000 2019,RT @G2Thijs: Thanks Blizzard for giving me a c...,403,18,133.5
23,Hearthstone,1209608880,Fri Apr 12 08:12:48 +0000 2019,RT @HSesports: Meet Europe's legendary lineup ...,304,55,129.7
24,Hearthstone,1209608880,Wed Apr 17 17:00:02 +0000 2019,Starting today you can grab a basketful of boo...,307,49,126.4
25,Hearthstone,1209608880,Thu Mar 21 17:05:44 +0000 2019,Join Game Designer Chadd Nervig as he introduc...,311,45,124.8
26,Hearthstone,1209608880,Tue Apr 02 19:29:51 +0000 2019,RT @HSesports: IN JUST 3 WEEKS the top 16 play...,286,55,124.3
27,Hearthstone,1209608880,Tue Apr 16 12:25:37 +0000 2019,RT @SilentNickHS: @PlayHearthstone #RiseOfShad...,313,40,121.9
28,Hearthstone,1209608880,Wed Mar 27 17:34:16 +0000 2019,RT @HSesports: The pinnacle of Hearthstone esp...,255,63,120.6
29,Hearthstone,1209608880,Mon Mar 25 16:47:55 +0000 2019,The first card reveal livestream is now live! ...,264,53,116.3
...,...,...,...,...,...,...,...
70,Hearthstone,1209608880,Sat Mar 30 19:49:53 +0000 2019,Sending the streets of Dalaran into chaos! #Ri...,122,10,43.6
71,Hearthstone,1209608880,Thu Apr 18 17:00:02 +0000 2019,Choose Your Champion is back for the HCT World...,98,19,42.7
72,Hearthstone,1209608880,Sat Mar 30 19:49:52 +0000 2019,As sinister plots are put into action by power...,123,8,42.5
73,Hearthstone,1209608880,Tue Apr 16 18:05:08 +0000 2019,Ever wanted to master the art of the mulligan?...,107,10,39.1
74,Hearthstone,1209608880,Fri Apr 05 09:20:37 +0000 2019,Now live! It is time for another exclusive Ris...,107,10,39.1
75,Hearthstone,1209608880,Fri Apr 19 13:46:24 +0000 2019,RT @HSTopDecks: HCT World Championship 2019 is...,83,17,36.8
76,Hearthstone,1209608880,Fri Apr 26 01:58:58 +0000 2019,RT @HSesports: We're LIVE! The action continue...,80,18,36.6
77,Hearthstone,1209608880,Thu Apr 11 17:00:02 +0000 2019,Looking to update your look before entering th...,91,13,36.4
78,Hearthstone,1209608880,Mon Apr 22 16:47:36 +0000 2019,This kicks off in just a few minutes at 10 AM ...,95,11,36.2
79,Hearthstone,1209608880,Wed Apr 10 16:00:01 +0000 2019,Embrace the shadows and celebrate the launch o...,96,10,35.8
80,Hearthstone,1209608880,Tue Apr 16 21:54:01 +0000 2019,The final results for Hearthstone Ranked Stand...,97,9,35.4
81,Hearthstone,1209608880,Sat Apr 06 17:00:02 +0000 2019,This weekend you can visit a @MicrosoftStore t...,87,8,31.7
82,Hearthstone,1209608880,Tue Apr 09 17:21:47 +0000 2019,Learn more about everything coming to Hearthst...,89,7,31.6
83,Hearthstone,1209608880,Mon Apr 01 22:12:32 +0000 2019,RT @Blizzard_ANZ: The only thing better than s...,77,8,28.7
84,Hearthstone,1209608880,Thu Apr 18 18:05:10 +0000 2019,Creator @F2K_Slysssa dives into the current st...,78,7,28.3
85,Hearthstone,1209608880,Tue Apr 02 23:06:34 +0000 2019,"RT @TeamTespa: This weekend, our Tespa chapter...",57,13,26.2
86,Hearthstone,1209608880,Fri Mar 29 21:43:21 +0000 2019,A few more locations have been added to the li...,71,6,25.5
87,Hearthstone,1209608880,Thu Apr 18 13:55:29 +0000 2019,Apologies to @PathraCadness for our original p...,76,2,24.2
88,Hearthstone,1209608880,Mon Apr 22 18:00:08 +0000 2019,Can you handle the metal? Guitarist @HaarasNC ...,57,8,22.7
89,Hearthstone,1209608880,Sat Mar 30 19:49:52 +0000 2019,Unseen dangers lurk around every corner! #Rise...,56,5,20.3
90,Hearthstone,1209608880,Thu Mar 21 17:51:46 +0000 2019,"@Jack_SwallowHS Hey, Hex showing a cost of 3-m...",15,1,5.2
91,Hearthstone,1209608880,Fri Apr 12 18:18:24 +0000 2019,@DaveKosak @CONNOR_RAPPER https://t.co/Osr2YjQY0s,9,1,3.4
92,Hearthstone,1209608880,Fri Apr 05 09:42:51 +0000 2019,"@LeBruce We also have French, German, Spanish,...",4,2,2.6
93,Hearthstone,1209608880,Mon Apr 08 19:06:36 +0000 2019,@HS_Disq The Rise of Shadows pre-purchase bund...,1,1,1.0
94,Hearthstone,1209608880,Fri Apr 12 18:16:22 +0000 2019,@FlashsquidInk @bmkibler Us today. https://t.c...,3,0,0.9
95,Hearthstone,1209608880,Fri Apr 12 18:11:35 +0000 2019,@FlashsquidInk @bmkibler https://t.co/YMd0FSzqhw,2,0,0.6
96,Hearthstone,1209608880,Fri Apr 12 18:09:33 +0000 2019,@FlashsquidInk @bmkibler It's fire. Or evil? O...,2,0,0.6
97,Hearthstone,1209608880,Fri Apr 12 18:17:32 +0000 2019,@CONNOR_RAPPER Your rap is much appreciated by...,1,0,0.3
98,Hearthstone,1209608880,Tue Apr 09 17:24:35 +0000 2019,@tankyy10 You may need to log back out and bac...,1,0,0.3
99,Hearthstone,1209608880,Thu Mar 21 17:34:36 +0000 2019,"@AI_Mechanic Hey, Hex showing a cost of 3-mana...",1,0,0.3

4.
CREATE VIEW `fourthview` AS
SELECT word , COUNT(*) as total 
FROM ( SELECT  User_id  , SUBSTRING_INDEX(SUBSTRING_INDEX(Post,' ',1),' ',-1) as word  FROM playhearthstone ) as t
GROUP BY word 
HAVING total >= 1 
ORDER BY total DESC

In [40]:
sql="SELECT * FROM project.fourthview;"
sql_to_df(sql)

                 word  total
0         @HSesports:      8
1                  to      7
2                 the      5
3                 you      5
4           @bmkibler      3
5                Your      3
6              League      3
7                  us      2
8               final      2
9                Hey,      2
10               some      2
11            weekend      2
12                few      2
13              kicks      1
14              today      1
15           thrilled      1
16               Rise      1
17              Brian      1
18      @YukieTAJIMA:      1
19              gear?      1
20                 as      1
21  @Thats_TowelieHS:      1
22              track      1
23            forget,      1
24                  a      1
25           sinister      1
26              weave      1
27               will      1
28            veteran      1
29               evil      1
..                ...    ...
37                 We      1
38      @LittleRedHS:      1
39             heroic      1
40     @DekkiGamesJP:      1
41               Game      1
42                 or      1
43       @F2K_Slysssa      1
44       @DorianGorr:      1
45              where      1
46              live!      1
47             mayhem      1
48             forget      1
49          partnered      1
50     @SilentNickHS:      1
51               more      1
52             today,      1
53          @G2Thijs:      1
54          Defenders      1
55              maybe      1
56                 of      1
57               Now!      1
58                how      1
59               Boom      1
60        @DaveKosak:      1
61     @CONNOR_RAPPER      1
62  @PlayHearthstone:      1
63               14.0      1
64     @Blizzard_ANZ:      1
65               Lead      1
66              first      1

[67 rows x 2 columns]

# Tag tables
The project require us to be able to tag the social media data that we collect.Therefore, we create four tables for I. Domain tags (tags in your domain)
II. Synonyms (which tags are synonyms?)
III. Mis-spellings (mis-spelled versions of words)
IV. Semantic information (categories of tags)
We insert the information we get from twitter to these table.

In [41]:
sql="select * from tag"
sql_to_df(sql)

,id,post,tag
0,1119279501102522369,Beat those pesky Bomb Warriors with our guide ...,#videogame
1,1119279665296945152,RT pcgamer: Beat those pesky Bomb Warriors wit...,hearthstone
2,1119281256464887808,RT @pcgamer: Beat those pesky Bomb Warriors wi...,[]
3,1119289469318893569,RT: @Bytecs1-RT pcgamer: Beat those pesky Bomb...,[]
4,1119289470916923392,RT: @Bytecs1-RT pcgamer: Beat those pesky Bomb...,[]
5,1119309428820332545,Hearthstone Malygos Rogue #456 Legend – @Siriu...,[]
6,1119309897273712640,RT @neon31HS: Hearthstone Malygos Rogue #456 L...,[]
7,1119387827832262657,RT @neon31HS: Hearthstone Malygos Rogue #456 L...,[]
8,1119636461387538433,@pwtenny if you ever need or want someone that...,[]
9,1119660281150541825,@JimmareHS @PlayHearthstone ??oOO Ive seen peo...,[{'text': 'hearthstone'}]
10,1119681719014252544,70% winrate Legend Bomb Hunter deck guide (Hea...,[]
11,1119752654861692928,RT @Old_GuardianHS: 70% winrate Legend Bomb Hu...,[]
12,1120030094720999425,KRIPP’S CRAFTING GUIDE - Rise of Shadows Heart...,[]
13,1120041900348792834,Legend Carpet Zoo Warlock deck guide (Hearthst...,[]
14,1120186252035276805,"Hey @Lanipator, I checked out your Villain Pal...",[]
15,1120240326231371776,Noblegarden is here on EU realms! New Hearthst...,[]
16,1120240326231371777,Noblegarden is here on EU realms! New Hearthst...,[]
17,1120241367706370048,RT @Wowhead: Noblegarden is here on EU realms!...,[]
18,1120241710980915205,RT @Wowhead: Noblegarden is here on EU realms!...,[]
19,1120242378390921216,@shink_hikari 自分は割と感覚的にプレイしてるのであんまり役に立たないですけど、...,[]
20,1120243709138747397,RT @Wowhead: Noblegarden is here on EU realms!...,[]
21,1120244373197860864,RT @Wowhead: Noblegarden is here on EU realms!...,[]
22,1120246164899729409,RT @Wowhead: Noblegarden is here on EU realms!...,[]
23,1120246409653960704,RT @Wowhead: Noblegarden is here on EU realms!...,[]
24,1120258614088929281,RT @Wowhead: Noblegarden is here on EU realms!...,[]
25,1120266546495070208,RT @Wowhead: Noblegarden is here on EU realms!...,[]
26,1120281448366448640,RT @Wowhead: Noblegarden is here on EU realms!...,[]
27,1120285195905785856,RT @Wowhead: Noblegarden is here on EU realms!...,[]
28,1120287515817148417,RT @Wowhead: Noblegarden is here on EU realms!...,[]
29,1120287822647193600,RT @Wowhead: Noblegarden is here on EU realms!...,[]
...,...,...,...
34,1120340854680379398,RT @Wowhead: Noblegarden is here on EU realms!...,[]
35,1120348093839360000,RT @Wowhead: Noblegarden is here on EU realms!...,[]
36,1120356061188382723,RT @Wowhead: Noblegarden is here on EU realms!...,[]
37,1120356831275180034,RT @Wowhead: Noblegarden is here on EU realms!...,[]
38,1120372925931098114,#hearthstone Giveaway \njoin the stream and tr...,[{'text': 'hearthstone'}]
39,1120387136719605760,RT @Wowhead: Noblegarden is here on EU realms!...,[]
40,1120388363348058114,RT @Wowhead: Noblegarden is here on EU realms!...,[]
41,1120391517829464064,RT @Wowhead: Noblegarden is here on EU realms!...,[]
42,1120392678628315137,The short guide to playing Hearthstone well ht...,[]
43,1120402166806654978,Reddit user /u/sepean put together a thoughtfu...,[{'text': 'Hearthstone'}]
44,1120402280333946880,RT @DaveKosak: Reddit user /u/sepean put toget...,[{'text': 'Hearthstone'}]
45,1120417608896065536,(Hearthstone) Tempo Rogue Guide April 2019 | *...,[{'text': 'RiseOfShadows'}]
46,1120425192008900612,RT @Guide_in_things: Бонус для новых игроков в...,[{'text': 'Hearthstone'}]
47,1120444519412043776,RT @Wowhead: Noblegarden is here on EU realms!...,[]
48,1120475472947707904,RT @Wowhead: Noblegarden is here on EU realms!...,[]
49,1120496505385828352,RT @DaveKosak: Reddit user /u/sepean put toget...,[{'text': 'Hearthstone'}]
50,1120645947200081920,[#Hearthstone] Rise of Shadows Legendary Craft...,[{'text': 'Hearthstone'}]
51,1120688023862218752,ICYMI [#Hearthstone] Rise of Shadows Legendary...,[{'text': 'Hearthstone'}]
52,1120693144759095298,RT @BlizzPro: ICYMI [#Hearthstone] Rise of Sha...,[{'text': 'Hearthstone'}]
53,1120768237426360320,"#hearthstone cmon guys, join us ??try your luc...",[{'text': 'hearthstone'}]
54,1120783741058727937,Legend Token Druid deck guide (Hearthstone Ris...,[]
55,1120787324307042304,RT @Old_GuardianHS: Legend Token Druid deck gu...,[]
56,1120873690340548613,RT @DaveKosak: Reddit user /u/sepean put toget...,[{'text': 'Hearthstone'}]
57,1121024906307809280,Hearthstone Legendary Crafting Guide (Standard...,"[{'text': 'Hearthstone'}, {'text': 'Videogames..."
58,1121025146729504770,RT @slyfx369: Hearthstone Legendary Crafting G...,"[{'text': 'Hearthstone'}, {'text': 'Videogames..."
59,1121473914754994178,#hearthstone #giveaway \n*OFERTA DO CORVO 15 P...,"[{'text': 'hearthstone'}, {'text': 'giveaway'}]"
60,1121526163766218754,[WILD] Hearthstone Token Druid #185 Legend – @...,[]
61,1121538849954512896,RT @neon31HS: [WILD] Hearthstone Token Druid #...,[]
62,1121596368773107712,#HCT World Championship 2019 Day 2 begins now!...,"[{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t..."
63,1121596459709870080,RT @Hearthpwn: #HCT World Championship 2019 Da...,"[{'text': 'HCT'}, {'text': 'Hearthstone'}, {'t..."

In [42]:
sql="select * from synonyms"
sql_to_df(sql)

Empty DataFrame
Columns: [id, synonyms, original_tag, post]
Index: []

In [45]:
sql="SELECT * FROM project.`mis-spelling`"
sql_to_df(sql)

Empty DataFrame
Columns: [id, post, misspelling tag, original_tag]
Index: []

In [46]:
sql="select * from semantic information"
sql_to_df(sql)

Empty DataFrame
Columns: [tag, semantic]
Index: []

In [47]:
sql="INSERT INTO tag (select id, post,hashtag as tag from game where post like '%hearthstone%')"

And, if we want add a tag for the post (for example id="1119279665296945152")

In [50]:
sql="select * from tag where id='1119309897273712640'"
sql_to_df(sql)

                    id                                               post tag
0  1119309897273712640  RT @neon31HS: Hearthstone Malygos Rogue #456 L...  []

In [52]:
sql="update tag set tag = 'hearthstone' where id = '1119279665296945152'"

In [53]:
sql="select * from tag where id='1119279665296945152'"
sql_to_df(sql)

,id,post,tag
0,1119279665296945152,RT pcgamer: Beat those pesky Bomb Warriors wit...,hearthstone

It is same when add tags in other tables.

# News
we are asked to create a newsfeed that presents news relevant to your projected audience. This
newsfeed must be updated automatically over time as new news comes in.

In [ ]:
from tweepy import Stream
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener
import time

In [ ]:
import json
CONSUMER_KEY = "40M3D2d9haFTmWiHUOqO3Wx7p"  
CONSUMER_SECRET = "FYdSd8Jcr5OmwQclQ1q1QwPLTwbVw3fX8Z35igJfqzmzLZp8d3"  
OAUTH_TOKEN = "1103068796036759552-iNLmsLjgYBODHZ1RcZBdsHG7g3d5wt"  
OAUTH_TOKEN_SECRET = "STv0EL4lsyamXzIYy6CZRE2wmml3toKuXQd5QDIV6nKtZ" 
auth = OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET)
#authorize api

In [ ]:
class StdOutListener(StreamListener):

    def __init__(self, api=None):
        super(StdOutListener, self).__init__()
        self.num_tweets = 0

    def on_status(self, status):
        record = {'news': status.text,'Created At': status.created_at}
        print (record)
        self.num_tweets += 1
        if self.num_tweets < 5:
            print (record)
            return (True)
        else:
            return (False)
    def on_error(self, status):
        print("error" )
    
#create function to return the news

In [ ]:
stream = Stream(auth, StdOutListener())

In [ ]:
def news(n):
    while True:
        print(stream.filter(track=["videogame"]))
        time.sleep(n)
#create the function to update the news automatically every n seconds

In [ ]:
news(3600)